#:schema https://github.com/arvinduh/formality/releases/download/s1.0/formality.schema.json
# formality configuration file
# https://github.com/arvinduh/formality

[global]
indent_size = 2
line_length = 80
end_of_line = "lf"
charset = "utf-8"
insert_final_newline = true
trim_trailing_whitespace = true
exclude = ["tests/fixtures/**", ".github/**", ".pre-commit-hooks.yaml"]

[lang.rust]
edition = "2024"

[lang.json]
exclude = ["editors/vscode/**"]
