use fml::cli::{Cli, Commands};
use fml::config::{FormalityConfig, ResolvedGlobalConfig};
use fml::editorconfig::{
  generate_editorconfig, generate_editorconfig_from_config,
};
use fml::surfaces::all_surfaces;
use std::fs;
use std::path::Path;
use tempfile::TempDir;

#[test]
fn test_editorconfig_generation_all_surfaces() {
  let global = ResolvedGlobalConfig::default();
  let surfaces = all_surfaces();
  let ec = generate_editorconfig(&global, &surfaces);

  // Header check
  assert!(ec.starts_with("# Auto-generated by formality. DO NOT EDIT."));
  assert!(ec.contains("root = true"));

  // [*] section check
  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\nindent_style = space\nindent_size = 2\nmax_line_length = 80"));

  // Surfaces matching [*] baseline are omitted
  assert!(!ec.contains("[*.rs]"));
  assert!(!ec.contains("[*.py]"));
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.{yaml,yml}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));
  assert!(!ec.contains("[*.typ]"));

  // JSON diverges due to unsupported line length
  assert!(ec.contains("[*.json]\nindent_style = space\nindent_size = 2\n"));
  assert!(!ec.contains(
    "[*.json]\nindent_style = space\nindent_size = 2\nmax_line_length"
  ));
}

#[test]
fn test_editorconfig_generation_customized_global_facets() {
  let global = ResolvedGlobalConfig {
    indent_size: 4,
    line_length: 120,
    end_of_line: "crlf".to_string(),
    use_tabs: true,
    insert_final_newline: false,
    trim_trailing_whitespace: false,
    ..ResolvedGlobalConfig::default()
  };

  let surfaces = all_surfaces();
  let ec = generate_editorconfig(&global, &surfaces);

  // Global [*]
  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = crlf\ninsert_final_newline = false\ntrim_trailing_whitespace = false\nindent_style = tab\nindent_size = 4\nmax_line_length = 120"));

  // Fixed spaces surfaces (diverge from tab)
  assert!(ec.contains(
    "[*.rs]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"
  ));
  assert!(ec.contains("[*.{yaml,yml}]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"));
  assert!(ec.contains(
    "[*.typ]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"
  ));

  // Configurable tabs surfaces match [*] and are omitted
  assert!(!ec.contains("[*.py]"));
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));

  // JSON is configurable for tabs, but unsupported for max_line_length (diverges from 120)
  assert!(ec.contains("[*.json]\nindent_style = tab\nindent_size = 4\n"));
}

#[test]
fn test_editorconfig_sync_command_workflow() {
  let temp = TempDir::new().unwrap();
  let root = temp.path().to_path_buf();

  // Create a rust project
  fs::write(
    root.join("Cargo.toml"),
    "[package]\nname = \"dummy\"\nversion = \"0.1.0\"",
  )
  .unwrap();
  fs::write(root.join("src.rs"), "fn main() {}").unwrap();

  // 1. sync --check should report drift for .editorconfig and .rustfmt.toml
  let check_args = Cli {
    config: None,
    root: Some(root.clone()),
    command: Commands::Sync {
      check: true,
      lang: vec![],
    },
  };
  let exit_drift = fml::run_with_args(check_args);
  assert_eq!(exit_drift, 1);

  // 2. Run sync to write files
  let write_args = Cli {
    config: None,
    root: Some(root.clone()),
    command: Commands::Sync {
      check: false,
      lang: vec![],
    },
  };
  let exit_write = fml::run_with_args(write_args);
  assert_eq!(exit_write, 0);

  // Verify .editorconfig was created
  let ec_path = root.join(".editorconfig");
  assert!(ec_path.is_file());
  let ec_content = fs::read_to_string(&ec_path).unwrap();
  assert!(
    ec_content.starts_with("# Auto-generated by formality. DO NOT EDIT.")
  );
  assert!(ec_content.contains("root = true"));
  assert!(ec_content.contains("[*]"));
  // In a default Rust project, rust settings match [*] baseline, so [*.rs] is omitted
  assert!(!ec_content.contains("[*.rs]"));

  // 3. sync --check should now pass cleanly
  let check_clean = Cli {
    config: None,
    root: Some(root.clone()),
    command: Commands::Sync {
      check: true,
      lang: vec![],
    },
  };
  let exit_clean = fml::run_with_args(check_clean);
  assert_eq!(exit_clean, 0);

  // 4. Modify .editorconfig manually to introduce drift
  fs::write(
    &ec_path,
    "# Auto-generated by formality. DO NOT EDIT.\nroot = false\n",
  )
  .unwrap();
  let check_drift_again = Cli {
    config: None,
    root: Some(root),
    command: Commands::Sync {
      check: true,
      lang: vec![],
    },
  };
  let exit_drift_again = fml::run_with_args(check_drift_again);
  assert_eq!(exit_drift_again, 1);
}

#[test]
fn test_editorconfig_manual_file_protection() {
  let temp = TempDir::new().unwrap();
  let root = temp.path().to_path_buf();

  // Create a rust file so detection finds a surface
  fs::write(root.join("main.rs"), "fn main() {}\n").unwrap();

  // Create handwritten .editorconfig without auto-gen header
  let custom_ec = "root = true\n\n[*]\nindent_size = 8\n";
  fs::write(root.join(".editorconfig"), custom_ec).unwrap();

  let write_args = Cli {
    config: None,
    root: Some(root.clone()),
    command: Commands::Sync {
      check: false,
      lang: vec![],
    },
  };
  let exit_code = fml::run_with_args(write_args);
  // Manual config should cause exit code 1 to alert user and not overwrite
  assert_eq!(exit_code, 1);

  let ec_after = fs::read_to_string(root.join(".editorconfig")).unwrap();
  assert_eq!(ec_after, custom_ec);
}

#[test]
fn test_editorconfig_with_per_language_overrides() {
  let temp = TempDir::new().unwrap();
  let root = temp.path().to_path_buf();

  let toml_content = r#"
[global]
indent_size = 2
line_length = 80

[lang.rust]
indent_size = 4
line_length = 100

[lang.python]
use_tabs = true
indent_size = 4
line_length = 88
"#;
  fs::write(root.join("formality.toml"), toml_content).unwrap();
  fs::write(root.join("main.rs"), "fn main() {}").unwrap();
  fs::write(root.join("app.py"), "print('hello')").unwrap();

  let config =
    FormalityConfig::parse_str(toml_content, Path::new("formality.toml"))
      .unwrap();
  let surfaces = all_surfaces();
  let ec = generate_editorconfig_from_config(&config, &surfaces);

  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\nindent_style = space\nindent_size = 2\nmax_line_length = 80"));
  assert!(ec.contains(
    "[*.rs]\nindent_style = space\nindent_size = 4\nmax_line_length = 100"
  ));
  assert!(ec.contains(
    "[*.py]\nindent_style = tab\nindent_size = 4\nmax_line_length = 88"
  ));

  // Surfaces matching [*] baseline are omitted
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.{yaml,yml}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));
  assert!(!ec.contains("[*.typ]"));

  // JSON still diverges on unsupported max_line_length
  assert!(ec.contains("[*.json]\nindent_style = space\nindent_size = 2\n"));
}
