mod common;

use common::{run_cli, sync_cmd, temp_repo};
use fml::config::{FormalityConfig, ResolvedGlobalConfig};
use fml::surfaces::all_surfaces;
use fml::surfaces::editorconfig::{
  generate_editorconfig, generate_editorconfig_from_config,
};
use std::fs;
use std::path::Path;

#[test]
fn test_editorconfig_generation_all_surfaces() {
  let global = ResolvedGlobalConfig::default();
  let surfaces = all_surfaces();
  let ec = generate_editorconfig(&global, &surfaces);

  // Header check
  assert!(ec.starts_with("# Auto-generated by formality. DO NOT EDIT."));
  assert!(ec.contains("root = true"));

  // [*] section check
  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\nindent_style = space\nindent_size = 2\nmax_line_length = 80"));

  // Surfaces matching [*] baseline are omitted
  assert!(!ec.contains("[*.rs]"));
  assert!(!ec.contains("[*.py]"));
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.{yaml,yml}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));
  assert!(!ec.contains("[*.typ]"));

  // JSON diverges due to unsupported line length
  assert!(ec.contains("[*.json]\nindent_style = space\nindent_size = 2\n"));
  assert!(!ec.contains(
    "[*.json]\nindent_style = space\nindent_size = 2\nmax_line_length"
  ));
}

#[test]
fn test_editorconfig_generation_customized_global_facets() {
  let global = ResolvedGlobalConfig {
    indent_size: 4,
    line_length: 120,
    end_of_line: "crlf".to_string(),
    use_tabs: true,
    insert_final_newline: false,
    trim_trailing_whitespace: false,
    ..ResolvedGlobalConfig::default()
  };

  let surfaces = all_surfaces();
  let ec = generate_editorconfig(&global, &surfaces);

  // Global [*]
  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = crlf\ninsert_final_newline = false\ntrim_trailing_whitespace = false\nindent_style = tab\nindent_size = 4\nmax_line_length = 120"));

  // Fixed spaces surfaces (diverge from tab)
  assert!(ec.contains(
    "[*.rs]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"
  ));
  assert!(ec.contains("[*.{yaml,yml}]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"));
  assert!(ec.contains(
    "[*.typ]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"
  ));

  // Configurable tabs surfaces match [*] and are omitted
  assert!(!ec.contains("[*.py]"));
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));

  // JSON is configurable for tabs, but unsupported for max_line_length (diverges from 120)
  assert!(ec.contains("[*.json]\nindent_style = tab\nindent_size = 4\n"));
}

#[test]
fn test_editorconfig_sync_command_workflow() {
  let temp = temp_repo(&[
    (
      "Cargo.toml",
      "[package]\nname = \"dummy\"\nversion = \"0.1.0\"",
    ),
    ("src.rs", "fn main() {}"),
  ]);
  let root = temp.path();

  // 1. sync --check should report drift for .editorconfig and .rustfmt.toml
  assert_eq!(run_cli(root, sync_cmd(true, &[])), 1);

  // 2. Run sync to write files
  assert_eq!(run_cli(root, sync_cmd(false, &[])), 0);

  // Verify .editorconfig was created
  let ec_path = root.join(".editorconfig");
  assert!(ec_path.is_file());
  let ec_content = fs::read_to_string(&ec_path).unwrap();
  assert!(
    ec_content.starts_with("# Auto-generated by formality. DO NOT EDIT.")
  );
  assert!(ec_content.contains("root = true"));
  assert!(ec_content.contains("[*]"));
  // In a default Rust project, rust settings match [*] baseline, so [*.rs] is omitted
  assert!(!ec_content.contains("[*.rs]"));

  // 3. sync --check should now pass cleanly
  assert_eq!(run_cli(root, sync_cmd(true, &[])), 0);

  // 4. Modify .editorconfig manually to introduce drift
  fs::write(
    &ec_path,
    "# Auto-generated by formality. DO NOT EDIT.\nroot = false\n",
  )
  .unwrap();
  assert_eq!(run_cli(root, sync_cmd(true, &[])), 1);
}

#[test]
fn test_editorconfig_manual_file_protection() {
  let custom_ec = "root = true\n\n[*]\nindent_size = 8\n";
  let temp =
    temp_repo(&[("main.rs", "fn main() {}\n"), (".editorconfig", custom_ec)]);
  let root = temp.path();

  // Manual config should cause exit code 1 to alert user and not overwrite
  assert_eq!(run_cli(root, sync_cmd(false, &[])), 1);

  let ec_after = fs::read_to_string(root.join(".editorconfig")).unwrap();
  assert_eq!(ec_after, custom_ec);
}

#[test]
fn test_editorconfig_with_per_language_overrides() {
  let toml_content = r"
[global]
indent_size = 2
line_length = 80

[lang.rust]
indent_size = 4
line_length = 100

[lang.python]
use_tabs = true
indent_size = 4
line_length = 88
";
  let _temp = temp_repo(&[
    ("formality.toml", toml_content),
    ("main.rs", "fn main() {}"),
    ("app.py", "print('hello')"),
  ]);

  let config =
    FormalityConfig::parse_str(toml_content, Path::new("formality.toml"))
      .unwrap();
  let surfaces = all_surfaces();
  let ec = generate_editorconfig_from_config(&config, &surfaces);

  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\nindent_style = space\nindent_size = 2\nmax_line_length = 80"));
  assert!(ec.contains(
    "[*.rs]\nindent_style = space\nindent_size = 4\nmax_line_length = 100"
  ));
  assert!(ec.contains(
    "[*.py]\nindent_style = tab\nindent_size = 4\nmax_line_length = 88"
  ));

  // Surfaces matching [*] baseline are omitted
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.{yaml,yml}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));
  assert!(!ec.contains("[*.typ]"));

  // JSON still diverges on unsupported max_line_length
  assert!(ec.contains("[*.json]\nindent_style = space\nindent_size = 2\n"));
}
