//! Guards the hand-applied local edits carried by the otherwise
//! dist-generated `.github/workflows/release.yml`.
//!
//! `Cargo.toml` sets `allow-dirty = ["ci"]`, which is what lets those edits
//! survive in the tree at all — but it also makes
//! `dist generate --mode=ci --check` refuse to run rather than report drift,
//! so dist itself can no longer tell anyone the edits are gone. Re-running
//! `dist generate --mode=ci --allow-dirty` after a cargo-dist bump silently
//! reverts every one of them, and the most dangerous revert
//! (`--generate-notes` back to dist's `--notes-file` changelog body) fails
//! *silently at release time*: this repo has no committed `CHANGELOG.md`, so
//! the published release body would simply be empty and nobody would notice
//! until a user looked at a release page.
//!
//! This test is the tooling behind the `# LOCAL EDIT (issue #134)` comments
//! in that workflow: a comment explains the edit, this asserts it is still
//! there. It runs in the `Library Tests` job (`cargo test --verbose`), the
//! repo's required status check, so losing an edit blocks the merge that
//! lost it instead of surfacing at the next release.
//!
//! **If a future cargo-dist version makes one of these edits unnecessary,
//! deleting the edit is one commit: drop its `LocalEdit` entry below and its
//! `# LOCAL EDIT` comment from the workflow.** Nothing else references them.

use std::fs;
use std::path::PathBuf;

/// The comment marker each local edit carries in the workflow. The count of
/// these is asserted to equal `EDITS.len()`, so an edit and its explanatory
/// comment can never drift apart.
const MARKER: &str = "# LOCAL EDIT (issue #134)";

/// One hand-applied edit to the dist-generated release workflow.
struct LocalEdit {
  /// Short name for the edit, used in the failure message.
  name: &'static str,
  /// Substrings that must still appear on a non-comment line of the
  /// workflow. Comment lines are excluded deliberately: the `LOCAL EDIT`
  /// comments quote what they replaced, and a quoted string in prose must
  /// not be able to satisfy (or trip) an assertion about live YAML.
  required: &'static [&'static str],
  /// Substrings dist's own generated output would reintroduce if the edit
  /// were reverted. Checked on non-comment lines only, for the same reason.
  forbidden: &'static [&'static str],
  /// What silently breaks if this edit is lost — quoted verbatim in the
  /// failure message so the reader does not have to go dig for the stakes.
  consequence: &'static str,
}

const EDITS: &[LocalEdit] = &[
  LocalEdit {
    name: "tag glob constrained to a leading `v`",
    required: &["- 'v[0-9]+.[0-9]+.[0-9]+*'"],
    forbidden: &["- '**[0-9]+.[0-9]+.[0-9]+*'"],
    consequence: "dist's default prefix-less glob also matches the `s*` schema tags owned \
       by schema-release.yml, so publishing a schema release would kick off a \
       full binary release.",
  },
  LocalEdit {
    name: "`fetch-depth: 0` on the host job's checkout",
    required: &["fetch-depth: 0"],
    forbidden: &[],
    consequence: "the shallow default checkout has no tag history, so the release step \
       cannot resolve the previous `v*` tag for --notes-start-tag.",
  },
  LocalEdit {
    name: "`gh release create --generate-notes --notes-start-tag`",
    required: &["--generate-notes", "--notes-start-tag"],
    forbidden: &["--notes-file"],
    consequence: "reverting to dist's --notes-file changelog body FAILS SILENTLY — this \
       repo has no committed CHANGELOG.md, so releases would publish with an \
       empty body and nothing would fail loudly.",
  },
];

/// Returns the workflow's lines with whole-line YAML comments removed, so
/// assertions only ever see live configuration.
fn non_comment_lines(workflow: &str) -> String {
  workflow
    .lines()
    .filter(|line| !line.trim_start().starts_with('#'))
    .collect::<Vec<_>>()
    .join("\n")
}

fn read_workflow() -> String {
  let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
    .join(".github")
    .join("workflows")
    .join("release.yml");
  assert!(
    path.exists(),
    ".github/workflows/release.yml not found. It is generated by \
     `dist generate --mode=ci --allow-dirty` and carries hand-applied local \
     edits; if the release pipeline has moved, update this test's path (and \
     the edit table in it) to match."
  );
  fs::read_to_string(&path)
    .expect("Failed to read .github/workflows/release.yml")
}

#[test]
fn test_release_yml_local_edits_survive() {
  let workflow = read_workflow();
  let live = non_comment_lines(&workflow);

  let mut failures: Vec<String> = Vec::new();

  for edit in EDITS {
    for needle in edit.required {
      if !live.contains(needle) {
        failures.push(format!(
          "LOST: {}\n    expected `{}` in .github/workflows/release.yml, not found\n    why it matters: {}",
          edit.name, needle, edit.consequence
        ));
      }
    }
    for needle in edit.forbidden {
      if live.contains(needle) {
        failures.push(format!(
          "REVERTED: {}\n    `{}` is back in .github/workflows/release.yml — that is dist's generated form, not this repo's\n    why it matters: {}",
          edit.name, needle, edit.consequence
        ));
      }
    }
  }

  assert!(
    failures.is_empty(),
    "\n\n.github/workflows/release.yml has lost {} of its hand-applied local edits:\n\n  {}\n\n\
     This file is generated by cargo-dist; `dist generate --mode=ci --allow-dirty` reverts these edits \
     without warning, and `allow-dirty = [\"ci\"]` in Cargo.toml means `dist generate --check` cannot report it. \
     To re-apply: each edit is described in a `{}` comment in the workflow explaining exactly what to change. \
     If those comments are gone too, recover them with `git log -p -- .github/workflows/release.yml` \
     (they were introduced in PR #156), and see docs/release.md for the release procedure.\n\
     If a cargo-dist upgrade genuinely made an edit unnecessary, delete its entry from EDITS in \
     tests/release_workflow_local_edits.rs in the same commit that drops the edit.\n",
    failures.len(),
    failures.join("\n\n  "),
    MARKER
  );
}

#[test]
fn test_release_yml_local_edits_are_each_documented() {
  let workflow = read_workflow();
  let found = workflow.matches(MARKER).count();

  assert_eq!(
    found,
    EDITS.len(),
    "\n\n.github/workflows/release.yml has {} `{}` comment(s), but {} local edit(s) are asserted in \
     tests/release_workflow_local_edits.rs. Every local edit must carry the marker comment explaining \
     why it exists and how to re-apply it after `dist generate` — that comment is the re-apply \
     instructions the assertion failure points readers at. Add the missing comment, or, if an edit was \
     deliberately dropped, remove its entry from EDITS in the same commit.\n",
    found,
    MARKER,
    EDITS.len()
  );
}
