//! `.editorconfig` generation from global facets and per-language overrides.

use std::path;

use fml::config;
use fml::surfaces;

#[test]
fn generation_all_surfaces() {
  let config = config::FormalityConfig::with_defaults();
  let surface_list = surfaces::registry::all_surfaces();
  let ec = surfaces::sync::editorconfig::generate_editorconfig_from_config(
    &config,
    &surface_list,
  );

  // Header check
  assert!(ec.starts_with("# Auto-generated by formality. DO NOT EDIT."));
  assert!(ec.contains("root = true"));

  // [*] section check
  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\nindent_style = space\nindent_size = 2\nmax_line_length = 80"));

  // Surfaces matching [*] baseline are omitted
  assert!(!ec.contains("[*.rs]"));
  assert!(!ec.contains("[*.py]"));
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.{yaml,yml}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));
  assert!(!ec.contains("[*.typ]"));

  // JSON diverges due to unsupported line length
  assert!(ec.contains("[*.json]\nindent_style = space\nindent_size = 2\n"));
  assert!(!ec.contains(
    "[*.json]\nindent_style = space\nindent_size = 2\nmax_line_length"
  ));
}

#[test]
fn generation_customized_global_facets() {
  let toml_content = r#"
[global]
indent_size = 4
line_length = 120
end_of_line = "crlf"
use_tabs = true
insert_final_newline = false
trim_trailing_whitespace = false
"#;
  let config = config::FormalityConfig::parse_str(
    toml_content,
    path::Path::new("formality.toml"),
  )
  .unwrap();

  let surface_list = surfaces::registry::all_surfaces();
  let ec = surfaces::sync::editorconfig::generate_editorconfig_from_config(
    &config,
    &surface_list,
  );

  // Global [*]
  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = crlf\ninsert_final_newline = false\ntrim_trailing_whitespace = false\nindent_style = tab\nindent_size = 4\nmax_line_length = 120"));

  // Fixed spaces surfaces (diverge from tab)
  assert!(ec.contains(
    "[*.rs]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"
  ));
  assert!(ec.contains("[*.{yaml,yml}]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"));
  assert!(ec.contains(
    "[*.typ]\nindent_style = space\nindent_size = 4\nmax_line_length = 120"
  ));

  // Configurable tabs surfaces match [*] and are omitted
  assert!(!ec.contains("[*.py]"));
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));

  // JSON is configurable for tabs, but unsupported for max_line_length (diverges from 120)
  assert!(ec.contains("[*.json]\nindent_style = tab\nindent_size = 4\n"));
}

#[test]
fn with_per_language_overrides() {
  let toml_content = r"
[global]
indent_size = 2
line_length = 80

[lang.rust]
indent_size = 4
line_length = 100

[lang.python]
use_tabs = true
indent_size = 4
line_length = 88
";
  let config = config::FormalityConfig::parse_str(
    toml_content,
    path::Path::new("formality.toml"),
  )
  .unwrap();
  let surface_list = surfaces::registry::all_surfaces();
  let ec = surfaces::sync::editorconfig::generate_editorconfig_from_config(
    &config,
    &surface_list,
  );

  assert!(ec.contains("[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\nindent_style = space\nindent_size = 2\nmax_line_length = 80"));
  assert!(ec.contains(
    "[*.rs]\nindent_style = space\nindent_size = 4\nmax_line_length = 100"
  ));
  assert!(ec.contains(
    "[*.py]\nindent_style = tab\nindent_size = 4\nmax_line_length = 88"
  ));

  // Surfaces matching [*] baseline are omitted
  assert!(!ec.contains("[*.{c,cc,cpp,cxx,h,hh,hpp,hxx}]"));
  assert!(!ec.contains("[*.{yaml,yml}]"));
  assert!(!ec.contains("[*.toml]"));
  assert!(!ec.contains("[*.md]"));
  assert!(!ec.contains("[*.typ]"));

  // JSON still diverges on unsupported max_line_length
  assert!(ec.contains("[*.json]\nindent_style = space\nindent_size = 2\n"));
}
