//! `fml sync`: writing and checking native tool configs.
//!
//! `.editorconfig` handling lives in `editorconfig`.

mod editorconfig;

use std::fs;

use crate::common;

use fml::engine::runner;

#[test]
fn config_workflow() {
  let temp = common::temp_repo(&[
    (
      "Cargo.toml",
      "[package]\nname = \"dummy\"\nversion = \"0.1.0\"",
    ),
    ("pyproject.toml", "[project]\nname = \"dummy\""),
    ("CMakeLists.txt", "project(dummy)"),
    ("README.md", "# Dummy"),
    ("data.json", "{}"),
    ("config.toml", ""),
  ]);
  let root = temp.path();

  // 1. Initial sync --check should detect missing native files (drift)
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(true, &[])),
    runner::ExitStatus::Violations
  );

  // 2. Run sync (write mode)
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(false, &[])),
    runner::ExitStatus::Clean
  );

  // Verify native files were created
  assert!(root.join(".rustfmt.toml").is_file());
  assert!(root.join("ruff.toml").is_file());
  assert!(root.join(".clang-format").is_file());
  assert!(root.join(".markdownlint.json").is_file());
  assert!(root.join(".prettierrc.json").is_file());
  assert!(root.join("taplo.toml").is_file());
  assert!(root.join(".editorconfig").is_file());

  // Check .editorconfig content
  let ec_content = fs::read_to_string(root.join(".editorconfig")).unwrap();
  assert!(ec_content.contains("root = true"));
  assert!(ec_content.contains("Auto-generated by formality. DO NOT EDIT."));
  assert!(ec_content.contains("[*]"));

  // Check .rustfmt.toml content
  let rustfmt_content = fs::read_to_string(root.join(".rustfmt.toml")).unwrap();
  assert!(rustfmt_content.contains("tab_spaces = 2"));
  assert!(rustfmt_content.contains("max_width = 80"));
  assert!(
    rustfmt_content.contains("Auto-generated by formality. DO NOT EDIT.")
  );
  assert!(rustfmt_content.contains("edition = \"2024\""));
  assert!(rustfmt_content.contains("reorder_imports = true"));

  // Check ruff.toml content
  let ruff_content = fs::read_to_string(root.join("ruff.toml")).unwrap();
  assert!(ruff_content.contains("line-length = 80"));
  assert!(ruff_content.contains("indent-width = 2"));
  assert!(ruff_content.contains("Auto-generated by formality. DO NOT EDIT."));

  // Check .clang-format content
  let clang_content = fs::read_to_string(root.join(".clang-format")).unwrap();
  assert!(clang_content.contains("IndentWidth: 2"));
  assert!(clang_content.contains("ColumnLimit: 80"));
  assert!(clang_content.contains("Auto-generated by formality. DO NOT EDIT."));

  // 3. Now sync --check should pass completely
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(true, &[])),
    runner::ExitStatus::Clean
  );

  // 4. Manually drift a file and check that drift is reported
  fs::write(
    root.join(".rustfmt.toml"),
    "tab_spaces = 8\nmax_width = 120",
  )
  .unwrap();
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(true, &["rust"])),
    runner::ExitStatus::Violations
  );
}
