//! `fml sync` writing `.editorconfig` and protecting a hand-written one.

use std::fs;

use crate::common;

use fml::engine::runner;

#[test]
fn sync_command_workflow() {
  let temp = common::temp_repo(&[
    (
      "Cargo.toml",
      "[package]\nname = \"dummy\"\nversion = \"0.1.0\"",
    ),
    ("src.rs", "fn main() {}"),
  ]);
  let root = temp.path();

  // 1. sync --check should report drift for .editorconfig and .rustfmt.toml
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(true, &[])),
    runner::ExitStatus::Violations
  );

  // 2. Run sync to write files
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(false, &[])),
    runner::ExitStatus::Clean
  );

  // Verify .editorconfig was created
  let ec_path = root.join(".editorconfig");
  assert!(ec_path.is_file());
  let ec_content = fs::read_to_string(&ec_path).unwrap();
  assert!(
    ec_content.starts_with("# Auto-generated by formality. DO NOT EDIT.")
  );
  assert!(ec_content.contains("root = true"));
  assert!(ec_content.contains("[*]"));
  // In a default Rust project, rust settings match [*] baseline, so [*.rs] is omitted
  assert!(!ec_content.contains("[*.rs]"));

  // 3. sync --check should now pass cleanly
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(true, &[])),
    runner::ExitStatus::Clean
  );

  // 4. Modify .editorconfig manually to introduce drift
  fs::write(
    &ec_path,
    "# Auto-generated by formality. DO NOT EDIT.\nroot = false\n",
  )
  .unwrap();
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(true, &[])),
    runner::ExitStatus::Violations
  );
}

#[test]
fn manual_file_protection() {
  let custom_ec = "root = true\n\n[*]\nindent_size = 8\n";
  let temp = common::temp_repo(&[
    ("main.rs", "fn main() {}\n"),
    (".editorconfig", custom_ec),
  ]);
  let root = temp.path();

  // Manual config should cause exit code 1 to alert user and not overwrite
  assert_eq!(
    common::run_cli(root, &common::sync_cmd(false, &[])),
    runner::ExitStatus::Violations
  );

  let ec_after = fs::read_to_string(root.join(".editorconfig")).unwrap();
  assert_eq!(ec_after, custom_ec);
}
