use super::{
  DeclaresFacets, ExecutionContext, Facet, FacetSupport, LanguageSurface,
  NativeConfig, SurfaceResult, SurfaceStatus, ToolInfo, check_binary_exists,
  create_tool_command, diff_check_via_tempcopy, find_files_with_ext,
  serialize_yaml_with_header, sync_file_helper,
};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::time::Instant;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "PascalCase")]
pub struct ClangFormatConfig {
  pub language: String,
  pub based_on_style: String,
  pub indent_width: usize,
  pub column_limit: usize,
  pub use_tab: String,
  pub line_ending: String,
}

impl NativeConfig for ClangFormatConfig {
  const FILE_NAME: &'static str = ".clang-format";
}

impl ClangFormatConfig {
  pub fn from_context(ctx: &ExecutionContext) -> Self {
    let use_tab = if ctx.lang_config.use_tabs {
      "Always"
    } else {
      "Never"
    };
    let line_ending =
      match ctx.global_config.end_of_line.to_lowercase().as_str() {
        "crlf" => "CRLF",
        "cr" => "CR",
        _ => "LF",
      };

    Self {
      language: "Cpp".to_string(),
      based_on_style: "LLVM".to_string(),
      indent_width: ctx.lang_config.indent_size,
      column_limit: ctx.lang_config.line_length,
      use_tab: use_tab.to_string(),
      line_ending: line_ending.to_string(),
    }
  }

  pub fn render(&self) -> Result<String, serde_yaml::Error> {
    serialize_yaml_with_header(self)
  }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "PascalCase")]
pub struct ClangTidyConfig {
  pub checks: String,
  pub warnings_as_errors: String,
  pub header_filter_regex: String,
  pub format_style: String,
}

impl NativeConfig for ClangTidyConfig {
  const FILE_NAME: &'static str = ".clang-tidy";
}

impl Default for ClangTidyConfig {
  fn default() -> Self {
    Self {
      checks:
        "*,-fuchsia-*,-google-readability-todo,-llvm-header-guard,-llvmlibc-*"
          .to_string(),
      warnings_as_errors: "".to_string(),
      header_filter_regex: "".to_string(),
      format_style: "none".to_string(),
    }
  }
}

impl ClangTidyConfig {
  pub fn from_context(_ctx: &ExecutionContext) -> Self {
    Self::default()
  }

  pub fn render(&self) -> Result<String, serde_yaml::Error> {
    serialize_yaml_with_header(self)
  }
}

#[derive(Debug, Default, Clone, Copy)]
pub struct CppSurface;

impl DeclaresFacets for CppSurface {
  fn facet_support(&self, facet: Facet) -> FacetSupport {
    match facet {
      Facet::IndentTabs => FacetSupport::Configurable,
      Facet::IndentWidth => FacetSupport::Configurable,
      Facet::LineLength => FacetSupport::Configurable,
      Facet::QuoteStyle => FacetSupport::Unsupported,
      Facet::TrailingComma => FacetSupport::Unsupported,
      Facet::ImportSort => FacetSupport::Configurable,
      Facet::ProseWrap => FacetSupport::Unsupported,
      Facet::Edition => FacetSupport::Unsupported,
      Facet::Standard => FacetSupport::Configurable,
    }
  }
}

pub const CPP_EXTENSIONS: &[&str] =
  &["c", "cpp", "cc", "cxx", "h", "hpp", "hxx"];

pub const CLANG_TIDY_TEMPLATE: &str = "# WARNING: DO NOT EDIT THIS FILE DIRECTLY! Automatically generated and managed by formality (fml). Canonical source of truth: formality.toml. Run 'fml sync' to update.
---
Checks: '*,-fuchsia-*,-google-readability-todo,-llvm-header-guard,-llvmlibc-*'
WarningsAsErrors: ''
HeaderFilterRegex: ''
FormatStyle: none
";

pub fn is_cpp_extension(ext: &str) -> bool {
  matches!(
    ext.to_ascii_lowercase().as_str(),
    "cpp" | "cc" | "cxx" | "hpp" | "hxx"
  )
}

pub fn is_c_extension(ext: &str) -> bool {
  ext.eq_ignore_ascii_case("c")
}

pub fn std_flag_for_file(file: &Path, all_files: &[PathBuf]) -> &'static str {
  let ext = file.extension().and_then(|e| e.to_str()).unwrap_or("");
  if is_cpp_extension(ext) {
    "-std=c++17"
  } else if is_c_extension(ext) {
    "-std=c17"
  } else if ext.eq_ignore_ascii_case("h") {
    let parent = file.parent();
    let has_cpp_in_list = all_files.iter().any(|f| {
      f.as_path() != file
        && f.parent() == parent
        && f
          .extension()
          .and_then(|e| e.to_str())
          .is_some_and(is_cpp_extension)
    });
    if has_cpp_in_list {
      "-std=c++17"
    } else if let Some(p) = parent
      && (p != Path::new("") || file.is_absolute())
      && let Ok(entries) = std::fs::read_dir(if p == Path::new("") {
        Path::new(".")
      } else {
        p
      })
    {
      let has_cpp_on_disk = entries.filter_map(Result::ok).any(|e| {
        let ep = e.path();
        ep.as_path() != file
          && ep
            .extension()
            .and_then(|ext| ext.to_str())
            .is_some_and(is_cpp_extension)
      });
      if has_cpp_on_disk {
        "-std=c++17"
      } else {
        "-std=c17"
      }
    } else {
      "-std=c17"
    }
  } else {
    "-std=c++17"
  }
}

pub fn build_clang_tidy_args(
  files: &[PathBuf],
  fix: bool,
  std_flag: &str,
  extra_args: &[String],
) -> Vec<String> {
  let mut args = Vec::new();
  if fix {
    args.push("-fix".to_string());
    args.push("-fix-errors".to_string());
  }
  for arg in extra_args {
    args.push(arg.clone());
  }
  for f in files {
    args.push(f.to_string_lossy().to_string());
  }
  args.push("--".to_string());
  args.push(std_flag.to_string());
  args
}

impl LanguageSurface for CppSurface {
  fn name(&self) -> &'static str {
    "cpp"
  }

  fn aliases(&self) -> &[&'static str] {
    &["c", "c++", "cxx"]
  }

  fn file_extensions(&self) -> &[&'static str] {
    CPP_EXTENSIONS
  }

  fn clone_box(&self) -> Box<dyn LanguageSurface> {
    Box::new(*self)
  }

  fn detect(&self, root: &Path) -> bool {
    root.join("CMakeLists.txt").is_file()
      || root.join("Makefile").is_file()
      || root.join("meson.build").is_file()
      || root.join(".clang-format").is_file()
      || root.join(".clang-tidy").is_file()
      || !find_files_with_ext(root, CPP_EXTENSIONS, &[], &[], &[]).is_empty()
  }

  fn tool_info(
    &self,
    _config: &crate::config::ResolvedLangConfig,
  ) -> Vec<ToolInfo> {
    vec![
      ToolInfo {
        binary: "clang-format",
        description: "C/C++ code formatter",
        install_hint: "Install via: sudo apt install clang-format (or brew install clang-format / pip install clang-format / winget install LLVM.LLVM)",
        is_required_for_fmt: true,
        is_required_for_lint: false,
      },
      ToolInfo {
        binary: "clang-tidy",
        description: "C/C++ linter and static analyzer",
        install_hint: "Install via: sudo apt install clang-tidy (or brew install llvm / winget install LLVM.LLVM)",
        is_required_for_fmt: false,
        is_required_for_lint: true,
      },
    ]
  }

  fn format(&self, ctx: &ExecutionContext) -> SurfaceResult {
    let start = Instant::now();

    if !check_binary_exists("clang-format") {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ToolMissing {
          binary: "clang-format".to_string(),
          install_hint:
            "sudo apt install clang-format / brew install clang-format / pip install clang-format / winget install LLVM.LLVM"
              .to_string(),
        },
        duration: start.elapsed(),
      };
    }

    let files = find_files_with_ext(
      &ctx.root,
      CPP_EXTENSIONS,
      &ctx.paths,
      &ctx.lang_config.files,
      &ctx.lang_config.exclude,
    );
    if files.is_empty() {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      };
    }

    if ctx.check_only {
      return diff_check_via_tempcopy(
        &files,
        |scratch| {
          let mut cmd = create_tool_command("clang-format");
          cmd.arg("-i").arg(scratch);
          cmd.args(&ctx.lang_config.extra_args);
          cmd.current_dir(&ctx.root);
          cmd.output()
        },
        self.name(),
        start,
      );
    }

    let mut cmd = create_tool_command("clang-format");
    cmd.arg("-i");

    for f in &files {
      cmd.arg(f);
    }

    cmd.args(&ctx.lang_config.extra_args);
    cmd.current_dir(&ctx.root);

    match cmd.output() {
      Ok(output) => {
        if output.status.success() {
          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::Passed,
            duration: start.elapsed(),
          }
        } else {
          let stderr = String::from_utf8_lossy(&output.stderr).to_string();
          let stdout = String::from_utf8_lossy(&output.stdout).to_string();
          let msg = if !stderr.trim().is_empty() {
            stderr
          } else if !stdout.trim().is_empty() {
            stdout
          } else {
            "Formatting violations found in C/C++ files".to_string()
          };

          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::ViolationsFound {
              message: msg,
              diff: None,
            },
            duration: start.elapsed(),
          }
        }
      }
      Err(e) => SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to execute clang-format: {}", e),
        },
        duration: start.elapsed(),
      },
    }
  }

  fn lint(&self, ctx: &ExecutionContext, fix: bool) -> SurfaceResult {
    let start = Instant::now();

    if !check_binary_exists("clang-tidy") {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ToolMissing {
          binary: "clang-tidy".to_string(),
          install_hint: "sudo apt install clang-tidy / brew install llvm / winget install LLVM.LLVM"
            .to_string(),
        },
        duration: start.elapsed(),
      };
    }

    let files = find_files_with_ext(
      &ctx.root,
      CPP_EXTENSIONS,
      &ctx.paths,
      &ctx.lang_config.files,
      &ctx.lang_config.exclude,
    );
    if files.is_empty() {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      };
    }

    let mut c_files = Vec::new();
    let mut cpp_files = Vec::new();

    for f in &files {
      let flag = std_flag_for_file(f, &files);
      if flag == "-std=c17" {
        c_files.push(f.clone());
      } else {
        cpp_files.push(f.clone());
      }
    }

    let groups: Vec<(Vec<PathBuf>, &'static str)> =
      [(c_files, "-std=c17"), (cpp_files, "-std=c++17")]
        .into_iter()
        .filter(|(flist, _)| !flist.is_empty())
        .collect();

    let mut failed_outputs = Vec::new();

    for (flist, std_flag) in groups {
      let mut cmd = create_tool_command("clang-tidy");
      let args = build_clang_tidy_args(
        &flist,
        fix,
        std_flag,
        &ctx.lang_config.extra_args,
      );
      cmd.args(&args);
      cmd.current_dir(&ctx.root);

      match cmd.output() {
        Ok(output) => {
          if !output.status.success() {
            failed_outputs.push(output);
          }
        }
        Err(e) => {
          return SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::ExecutionError {
              message: format!("Failed to execute clang-tidy: {}", e),
            },
            duration: start.elapsed(),
          };
        }
      }
    }

    if failed_outputs.is_empty() {
      SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      }
    } else {
      let mut msgs = Vec::new();
      for output in failed_outputs {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let msg = if !stderr.trim().is_empty() {
          stderr
        } else {
          stdout
        };
        if !msg.trim().is_empty() {
          msgs.push(msg);
        }
      }
      let final_msg = if msgs.is_empty() {
        "clang-tidy violations found".to_string()
      } else {
        msgs.join("\n")
      };

      SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ViolationsFound {
          message: final_msg,
          diff: None,
        },
        duration: start.elapsed(),
      }
    }
  }

  fn sync_config(&self, ctx: &ExecutionContext, check: bool) -> SurfaceResult {
    let start = Instant::now();
    let format_target = ctx.root.join(ClangFormatConfig::FILE_NAME);
    let format_cfg = ClangFormatConfig::from_context(ctx);
    let format_content = match format_cfg.render() {
      Ok(c) => c,
      Err(e) => {
        return SurfaceResult {
          surface_name: self.name(),
          status: SurfaceStatus::ExecutionError {
            message: format!(
              "Failed to serialize {}: {}",
              ClangFormatConfig::FILE_NAME,
              e
            ),
          },
          duration: start.elapsed(),
        };
      }
    };

    let format_res = sync_file_helper(
      &format_target,
      ClangFormatConfig::FILE_NAME,
      &format_content,
      check,
      start,
      self.name(),
    );

    if !format_res.is_success() {
      return format_res;
    }

    let tidy_res = sync_clang_tidy_config(ctx, check, start, self.name());
    if !tidy_res.is_success() {
      return tidy_res;
    }

    if matches!(tidy_res.status, SurfaceStatus::ConfigSynced { .. }) {
      tidy_res
    } else {
      format_res
    }
  }
}

pub fn sync_clang_tidy_config(
  ctx: &ExecutionContext,
  check: bool,
  start: Instant,
  surface_name: &'static str,
) -> SurfaceResult {
  let target = ctx.root.join(ClangTidyConfig::FILE_NAME);
  let tidy_cfg = ClangTidyConfig::from_context(ctx);
  let content = match tidy_cfg.render() {
    Ok(c) => c,
    Err(e) => {
      return SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!(
            "Failed to serialize {}: {}",
            ClangTidyConfig::FILE_NAME,
            e
          ),
        },
        duration: start.elapsed(),
      };
    }
  };

  sync_file_helper(
    &target,
    ClangTidyConfig::FILE_NAME,
    &content,
    check,
    start,
    surface_name,
  )
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::FormalityConfig;
  use tempfile::tempdir;

  #[test]
  fn test_std_flag_for_c_files() {
    let all_files =
      vec![PathBuf::from("src/main.c"), PathBuf::from("src/utils.c")];
    assert_eq!(
      std_flag_for_file(Path::new("src/main.c"), &all_files),
      "-std=c17"
    );
    assert_eq!(
      std_flag_for_file(Path::new("src/utils.c"), &all_files),
      "-std=c17"
    );
  }

  #[test]
  fn test_std_flag_for_cpp_files() {
    let all_files = vec![
      PathBuf::from("src/main.cpp"),
      PathBuf::from("src/app.cc"),
      PathBuf::from("src/engine.cxx"),
      PathBuf::from("src/math.hpp"),
      PathBuf::from("src/types.hxx"),
    ];
    assert_eq!(
      std_flag_for_file(Path::new("src/main.cpp"), &all_files),
      "-std=c++17"
    );
    assert_eq!(
      std_flag_for_file(Path::new("src/app.cc"), &all_files),
      "-std=c++17"
    );
    assert_eq!(
      std_flag_for_file(Path::new("src/engine.cxx"), &all_files),
      "-std=c++17"
    );
    assert_eq!(
      std_flag_for_file(Path::new("src/math.hpp"), &all_files),
      "-std=c++17"
    );
    assert_eq!(
      std_flag_for_file(Path::new("src/types.hxx"), &all_files),
      "-std=c++17"
    );
  }

  #[test]
  fn test_std_flag_for_header_without_cpp_siblings() {
    let all_files =
      vec![PathBuf::from("src/main.c"), PathBuf::from("src/utils.h")];
    assert_eq!(
      std_flag_for_file(Path::new("src/utils.h"), &all_files),
      "-std=c17"
    );
  }

  #[test]
  fn test_std_flag_for_header_with_cpp_siblings() {
    let all_files =
      vec![PathBuf::from("src/main.cpp"), PathBuf::from("src/utils.h")];
    assert_eq!(
      std_flag_for_file(Path::new("src/utils.h"), &all_files),
      "-std=c++17"
    );
  }

  #[test]
  fn test_std_flag_for_header_on_disk_detection() {
    let dir = tempdir().unwrap();
    let c_dir = dir.path().join("c_code");
    std::fs::create_dir_all(&c_dir).unwrap();
    let c_header = c_dir.join("header.h");
    let c_source = c_dir.join("source.c");
    std::fs::write(&c_header, "").unwrap();
    std::fs::write(&c_source, "").unwrap();

    let cpp_dir = dir.path().join("cpp_code");
    std::fs::create_dir_all(&cpp_dir).unwrap();
    let cpp_header = cpp_dir.join("header.h");
    let cpp_source = cpp_dir.join("source.cpp");
    std::fs::write(&cpp_header, "").unwrap();
    std::fs::write(&cpp_source, "").unwrap();

    assert_eq!(std_flag_for_file(&c_header, &[]), "-std=c17");
    assert_eq!(std_flag_for_file(&cpp_header, &[]), "-std=c++17");
  }

  #[test]
  fn test_build_clang_tidy_args_without_fix() {
    let files = vec![PathBuf::from("src/main.c"), PathBuf::from("src/utils.c")];
    let extra_args = vec!["--checks=*".to_string()];
    let args = build_clang_tidy_args(&files, false, "-std=c17", &extra_args);
    assert_eq!(
      args,
      vec![
        "--checks=*".to_string(),
        "src/main.c".to_string(),
        "src/utils.c".to_string(),
        "--".to_string(),
        "-std=c17".to_string(),
      ]
    );
  }

  #[test]
  fn test_build_clang_tidy_args_with_fix() {
    let files = vec![PathBuf::from("src/app.cpp")];
    let args = build_clang_tidy_args(&files, true, "-std=c++17", &[]);
    assert_eq!(
      args,
      vec![
        "-fix".to_string(),
        "-fix-errors".to_string(),
        "src/app.cpp".to_string(),
        "--".to_string(),
        "-std=c++17".to_string(),
      ]
    );
  }

  #[test]
  fn test_clang_tidy_template_content() {
    assert!(
      CLANG_TIDY_TEMPLATE.contains("WARNING: DO NOT EDIT THIS FILE DIRECTLY!")
    );
    assert!(CLANG_TIDY_TEMPLATE.contains("Checks: '*,-fuchsia-*,-google-readability-todo,-llvm-header-guard,-llvmlibc-*'"));
    assert!(CLANG_TIDY_TEMPLATE.contains("WarningsAsErrors: ''"));
    assert!(CLANG_TIDY_TEMPLATE.contains("HeaderFilterRegex: ''"));
    assert!(CLANG_TIDY_TEMPLATE.contains("FormatStyle: none"));
  }

  #[test]
  fn test_sync_config_generates_clang_tidy_and_clang_format() {
    let dir = tempdir().unwrap();
    let root = dir.path().to_path_buf();

    let cfg = FormalityConfig::default();
    let ctx = ExecutionContext {
      root: root.clone(),
      paths: Vec::new(),
      global_config: cfg.resolve_global(),
      lang_config: cfg.resolve_for_lang("cpp"),
      check_only: false,
    };

    let surface = CppSurface;
    let res = surface.sync_config(&ctx, false);
    assert!(res.is_success());

    let format_path = root.join(".clang-format");
    let tidy_path = root.join(".clang-tidy");

    assert!(format_path.is_file());
    assert!(tidy_path.is_file());

    let format_content = std::fs::read_to_string(&format_path).unwrap();
    let tidy_content = std::fs::read_to_string(&tidy_path).unwrap();

    assert!(format_content.contains("Language: Cpp"));
    assert!(tidy_content.contains("Checks: '*,-fuchsia-*,-google-readability-todo,-llvm-header-guard,-llvmlibc-*'"));

    let check_res = surface.sync_config(&ctx, true);
    assert!(matches!(check_res.status, SurfaceStatus::Passed));
  }
  #[test]
  fn test_clang_format_config_typed_serialization() {
    let cfg = ClangFormatConfig {
      language: "Cpp".to_string(),
      based_on_style: "LLVM".to_string(),
      indent_width: 4,
      column_limit: 100,
      use_tab: "Never".to_string(),
      line_ending: "LF".to_string(),
    };
    let rendered = cfg.render().unwrap();
    assert!(rendered.starts_with(crate::surfaces::AUTO_GENERATED_HEADER));
    assert!(rendered.contains("Language: Cpp"));
    assert!(rendered.contains("BasedOnStyle: LLVM"));
    assert!(rendered.contains("IndentWidth: 4"));
    assert!(rendered.contains("ColumnLimit: 100"));
    assert!(rendered.contains("UseTab: Never"));
    assert!(rendered.contains("LineEnding: LF"));
  }

  #[test]
  fn test_clang_tidy_config_typed_serialization() {
    let cfg = ClangTidyConfig::default();
    let rendered = cfg.render().unwrap();
    assert!(rendered.starts_with(crate::surfaces::AUTO_GENERATED_HEADER));
    assert!(rendered.contains("Checks:"));
    assert!(rendered.contains("FormatStyle: none"));
  }
}
