use super::{
  DeclaresFacets, ExecutionContext, Facet, FacetSupport, LanguageSurface,
  NativeConfig, SurfaceResult, SurfaceStatus, ToolInfo, check_binary_exists,
  create_tool_command, diff_check_via_tempcopy, find_files_with_ext,
  sync_file_helper,
};
use serde::{Deserialize, Serialize};
use std::path::Path;
use std::time::Instant;

/// Typed configuration for Checkstyle, rendered as a Checkstyle XML module
/// tree. Deliberately mirrors what `google-java-format` actually enforces
/// (2-space indentation, 100-column lines) rather than the user's generic
/// layout facets, so that `fml fmt` output always passes `fml lint`
/// immediately afterward ("Smart Format").
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CheckstyleConfig {
  pub line_length: usize,
  pub indent_size: usize,
  pub check_unused_imports: bool,
  pub check_import_order: bool,
}

impl NativeConfig for CheckstyleConfig {
  const FILE_NAME: &'static str = "checkstyle.xml";
}

impl CheckstyleConfig {
  pub fn from_context(ctx: &ExecutionContext) -> Self {
    let java_opts = ctx.lang_config.java.as_ref();
    let aosp = java_opts.and_then(|j| j.style.as_deref()) == Some("aosp");
    let indent_size = if aosp { 4 } else { 2 };

    Self {
      // google-java-format enforces a fixed 100-column limit; there is no
      // knob to change it, so the generated lint config mirrors that rather
      // than the user's generic `line_length` facet.
      line_length: 100,
      indent_size,
      check_unused_imports: true,
      check_import_order: true,
    }
  }

  pub fn render(&self) -> String {
    let import_order_module = if self.check_import_order {
      "\n    <module name=\"ImportOrder\">\n      <property name=\"ordered\" value=\"true\"/>\n      <property name=\"separated\" value=\"true\"/>\n    </module>"
    } else {
      ""
    };
    let unused_imports_module = if self.check_unused_imports {
      "\n    <module name=\"UnusedImports\"/>"
    } else {
      ""
    };

    format!(
      "<?xml version=\"1.0\"?>\n\
<!DOCTYPE module PUBLIC\n\
    \"-//Checkstyle//DTD Checkstyle Configuration 1.3//EN\"\n\
    \"https://checkstyle.org/dtds/configuration_1_3.dtd\">\n\
<!-- WARNING: DO NOT EDIT THIS FILE DIRECTLY! Automatically generated and managed by formality (fml). Canonical source of truth: formality.toml. Run 'fml sync' to update. -->\n\
<module name=\"Checker\">\n\
  <property name=\"charset\" value=\"UTF-8\"/>\n\
  <property name=\"severity\" value=\"warning\"/>\n\
  <module name=\"LineLength\">\n\
    <property name=\"max\" value=\"{line_length}\"/>\n\
  </module>\n\
  <module name=\"TreeWalker\">\n\
    <module name=\"Indentation\">\n\
      <property name=\"basicOffset\" value=\"{indent_size}\"/>\n\
    </module>\n\
    <module name=\"RedundantImport\"/>{unused_imports_module}{import_order_module}\n\
  </module>\n\
</module>\n",
      line_length = self.line_length,
      indent_size = self.indent_size,
      unused_imports_module = unused_imports_module,
      import_order_module = import_order_module,
    )
  }
}

#[derive(Debug, Default, Clone, Copy)]
pub struct JavaSurface;

impl DeclaresFacets for JavaSurface {
  fn facet_support(&self, facet: Facet) -> FacetSupport {
    match facet {
      // google-java-format never uses tabs.
      Facet::IndentTabs => FacetSupport::Fixed("spaces"),
      // Indentation is dictated by the chosen style (Google = 2, AOSP = 4),
      // not freely configurable per-project.
      Facet::IndentWidth => FacetSupport::Fixed("2"),
      // google-java-format hardcodes a 100-column limit; there is no flag
      // to change it.
      Facet::LineLength => FacetSupport::Fixed("100"),
      Facet::QuoteStyle => FacetSupport::Unsupported,
      Facet::TrailingComma => FacetSupport::Unsupported,
      // Import organization/sorting happens automatically as part of
      // `google-java-format --replace`, and is checked via Checkstyle's
      // ImportOrder/UnusedImports modules.
      Facet::ImportSort => FacetSupport::Configurable,
      Facet::ProseWrap => FacetSupport::Unsupported,
      Facet::Edition => FacetSupport::Unsupported,
      // Google vs AOSP style, surfaced via `[lang.java] style = "aosp"`.
      Facet::Standard => FacetSupport::Configurable,
    }
  }
}

pub const JAVA_EXTENSIONS: &[&str] = &["java"];

fn is_aosp_style(ctx: &ExecutionContext) -> bool {
  ctx
    .lang_config
    .java
    .as_ref()
    .and_then(|j| j.style.as_deref())
    == Some("aosp")
}

impl LanguageSurface for JavaSurface {
  fn name(&self) -> &'static str {
    "java"
  }

  fn aliases(&self) -> &[&'static str] {
    &["jav"]
  }

  fn file_extensions(&self) -> &[&'static str] {
    JAVA_EXTENSIONS
  }

  fn clone_box(&self) -> Box<dyn LanguageSurface> {
    Box::new(*self)
  }

  fn supports_lint_fix(&self) -> bool {
    false
  }

  fn detect(&self, root: &Path) -> bool {
    root.join("pom.xml").is_file()
      || root.join("build.gradle").is_file()
      || root.join("build.gradle.kts").is_file()
      || root.join("checkstyle.xml").is_file()
      || !find_files_with_ext(root, JAVA_EXTENSIONS, &[], &[], &[]).is_empty()
  }

  fn tool_info(
    &self,
    _config: &crate::config::ResolvedLangConfig,
  ) -> Vec<ToolInfo> {
    vec![
      ToolInfo {
        binary: "google-java-format",
        description: "Java code formatter with built-in import organizing",
        install_hint: "Install via: brew install google-java-format (or download the all-deps jar from https://github.com/google/google-java-format/releases and place a 'google-java-format' wrapper on PATH)",
        is_required_for_fmt: true,
        is_required_for_lint: false,
      },
      ToolInfo {
        binary: "checkstyle",
        description: "Java static analysis / style linter",
        install_hint: "Install via: brew install checkstyle (or download from https://checkstyle.org and place a 'checkstyle' wrapper on PATH)",
        is_required_for_fmt: false,
        is_required_for_lint: true,
      },
    ]
  }

  fn format(&self, ctx: &ExecutionContext) -> SurfaceResult {
    let start = Instant::now();

    if !check_binary_exists("google-java-format") {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ToolMissing {
          binary: "google-java-format".to_string(),
          install_hint:
            "brew install google-java-format / download the all-deps jar from https://github.com/google/google-java-format/releases"
              .to_string(),
        },
        duration: start.elapsed(),
      };
    }

    let files = find_files_with_ext(
      &ctx.root,
      JAVA_EXTENSIONS,
      &ctx.paths,
      &ctx.lang_config.files,
      &ctx.lang_config.exclude,
    );
    if files.is_empty() {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      };
    }

    let aosp = is_aosp_style(ctx);

    // A single `--replace` invocation both formats and organizes/sorts
    // imports (Smart Format): google-java-format's pretty-printer always
    // reorders and de-duplicates imports as part of normal formatting, so
    // there is no separate import-sort pass needed like Python's ruff.
    if ctx.check_only {
      return diff_check_via_tempcopy(
        &files,
        |scratch| {
          let mut cmd = create_tool_command("google-java-format");
          if aosp {
            cmd.arg("--aosp");
          }
          cmd.arg("--replace").arg(scratch);
          cmd.args(&ctx.lang_config.extra_args);
          cmd.current_dir(&ctx.root);
          cmd.output()
        },
        self.name(),
        start,
      );
    }

    let mut cmd = create_tool_command("google-java-format");
    if aosp {
      cmd.arg("--aosp");
    }
    cmd.arg("--replace");

    for f in &files {
      cmd.arg(f);
    }

    cmd.args(&ctx.lang_config.extra_args);
    cmd.current_dir(&ctx.root);

    match cmd.output() {
      Ok(output) => {
        if output.status.success() {
          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::Passed,
            duration: start.elapsed(),
          }
        } else {
          let stderr = String::from_utf8_lossy(&output.stderr).to_string();
          let stdout = String::from_utf8_lossy(&output.stdout).to_string();
          let msg = if !stderr.trim().is_empty() {
            stderr
          } else if !stdout.trim().is_empty() {
            stdout
          } else {
            "Formatting violations found in Java files".to_string()
          };

          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::ViolationsFound {
              message: msg,
              diff: None,
            },
            duration: start.elapsed(),
          }
        }
      }
      Err(e) => SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to execute google-java-format: {}", e),
        },
        duration: start.elapsed(),
      },
    }
  }

  fn lint(&self, ctx: &ExecutionContext, fix: bool) -> SurfaceResult {
    let start = Instant::now();

    if fix {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Skipped {
          reason: "Tool does not support autofix; run fml fmt instead"
            .to_string(),
        },
        duration: start.elapsed(),
      };
    }

    if !check_binary_exists("checkstyle") {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ToolMissing {
          binary: "checkstyle".to_string(),
          install_hint:
            "brew install checkstyle / download from https://checkstyle.org"
              .to_string(),
        },
        duration: start.elapsed(),
      };
    }

    let files = find_files_with_ext(
      &ctx.root,
      JAVA_EXTENSIONS,
      &ctx.paths,
      &ctx.lang_config.files,
      &ctx.lang_config.exclude,
    );
    if files.is_empty() {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      };
    }

    // Checkstyle requires an explicit `-c` config; self-heal by generating
    // the standard formality-managed checkstyle.xml if `fml sync` hasn't
    // been run yet, so `fml lint` still works out of the box.
    let config_path = ctx.root.join(CheckstyleConfig::FILE_NAME);
    if !config_path.is_file() {
      let cfg = CheckstyleConfig::from_context(ctx);
      let _ = std::fs::write(&config_path, cfg.render());
    }

    let mut cmd = create_tool_command("checkstyle");
    cmd.arg("-c").arg(&config_path);
    for f in &files {
      cmd.arg(f);
    }
    cmd.args(&ctx.lang_config.extra_args);
    cmd.current_dir(&ctx.root);

    match cmd.output() {
      Ok(output) => {
        // Checkstyle exits 0 even when it reports "warning" severity
        // findings (it only fails the process on "error" severity or
        // higher), so treat any diagnostic-bearing output as a violation.
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        let has_findings = stdout.contains("WARN") || stdout.contains("ERROR");

        if output.status.success() && !has_findings {
          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::Passed,
            duration: start.elapsed(),
          }
        } else {
          let msg = if !stdout.trim().is_empty() {
            stdout
          } else if !stderr.trim().is_empty() {
            stderr
          } else {
            "Checkstyle violations found in Java files".to_string()
          };

          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::ViolationsFound {
              message: msg,
              diff: None,
            },
            duration: start.elapsed(),
          }
        }
      }
      Err(e) => SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to execute checkstyle: {}", e),
        },
        duration: start.elapsed(),
      },
    }
  }

  fn sync_config(&self, ctx: &ExecutionContext, check: bool) -> SurfaceResult {
    let start = Instant::now();
    let target = ctx.root.join(CheckstyleConfig::FILE_NAME);
    let cfg = CheckstyleConfig::from_context(ctx);
    let content = cfg.render();

    sync_file_helper(
      &target,
      CheckstyleConfig::FILE_NAME,
      &content,
      check,
      start,
      self.name(),
    )
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::{JavaOptions, ResolvedGlobalConfig, ResolvedLangConfig};
  use tempfile::TempDir;

  #[test]
  fn test_java_facet_support() {
    let surface = JavaSurface;
    assert_eq!(
      surface.facet_support(Facet::IndentTabs),
      FacetSupport::Fixed("spaces")
    );
    assert_eq!(
      surface.facet_support(Facet::IndentWidth),
      FacetSupport::Fixed("2")
    );
    assert_eq!(
      surface.facet_support(Facet::LineLength),
      FacetSupport::Fixed("100")
    );
    assert_eq!(
      surface.facet_support(Facet::ImportSort),
      FacetSupport::Configurable
    );
    assert_eq!(
      surface.facet_support(Facet::QuoteStyle),
      FacetSupport::Unsupported
    );
  }

  #[test]
  fn test_java_surface_aliases_and_extensions() {
    let surface = JavaSurface;
    assert_eq!(surface.name(), "java");
    assert_eq!(surface.aliases(), &["jav"]);
    assert_eq!(surface.file_extensions(), &["java"]);
    assert!(!surface.supports_lint_fix());
  }

  #[test]
  fn test_java_detect_by_build_files() {
    let temp = TempDir::new().unwrap();
    let surface = JavaSurface;
    assert!(!surface.detect(temp.path()));

    std::fs::write(temp.path().join("pom.xml"), "<project></project>").unwrap();
    assert!(surface.detect(temp.path()));
  }

  #[test]
  fn test_java_detect_by_source_file() {
    let temp = TempDir::new().unwrap();
    let surface = JavaSurface;
    std::fs::write(temp.path().join("Main.java"), "class Main {}\n").unwrap();
    assert!(surface.detect(temp.path()));
  }

  #[test]
  fn test_checkstyle_config_render_google_style() {
    let cfg = CheckstyleConfig {
      line_length: 100,
      indent_size: 2,
      check_unused_imports: true,
      check_import_order: true,
    };
    let rendered = cfg.render();
    assert!(rendered.contains("DO NOT EDIT THIS FILE DIRECTLY!"));
    assert!(rendered.contains("<property name=\"max\" value=\"100\"/>"));
    assert!(rendered.contains("<property name=\"basicOffset\" value=\"2\"/>"));
    assert!(rendered.contains("<module name=\"UnusedImports\"/>"));
    assert!(rendered.contains("<module name=\"ImportOrder\">"));
    assert!(rendered.contains("<module name=\"RedundantImport\"/>"));
  }

  #[test]
  fn test_checkstyle_config_from_context_aosp_style() {
    let temp = TempDir::new().unwrap();
    let mut lang_cfg = ResolvedLangConfig::new("java");
    lang_cfg.java = Some(JavaOptions {
      style: Some("aosp".to_string()),
    });

    let ctx = ExecutionContext {
      root: temp.path().to_path_buf(),
      paths: Vec::new(),
      global_config: ResolvedGlobalConfig::default(),
      lang_config: lang_cfg,
      check_only: false,
    };

    let cfg = CheckstyleConfig::from_context(&ctx);
    assert_eq!(cfg.indent_size, 4);
    assert_eq!(cfg.line_length, 100);
  }

  #[test]
  fn test_java_sync_config_generates_checkstyle_xml() {
    let temp = TempDir::new().unwrap();
    let root = temp.path().to_path_buf();

    let ctx = ExecutionContext {
      root: root.clone(),
      paths: Vec::new(),
      global_config: ResolvedGlobalConfig::default(),
      lang_config: ResolvedLangConfig::new("java"),
      check_only: false,
    };

    let surface = JavaSurface;
    let res = surface.sync_config(&ctx, false);
    assert!(res.is_success());

    let config_path = root.join("checkstyle.xml");
    assert!(config_path.is_file());

    let content = std::fs::read_to_string(&config_path).unwrap();
    assert!(content.contains("Checker"));
    assert!(content.contains("basicOffset"));

    let check_res = surface.sync_config(&ctx, true);
    assert!(matches!(check_res.status, SurfaceStatus::Passed));
  }

  #[test]
  fn test_is_aosp_style_default_false() {
    let temp = TempDir::new().unwrap();
    let ctx = ExecutionContext {
      root: temp.path().to_path_buf(),
      paths: Vec::new(),
      global_config: ResolvedGlobalConfig::default(),
      lang_config: ResolvedLangConfig::new("java"),
      check_only: false,
    };
    assert!(!is_aosp_style(&ctx));
  }

  #[test]
  fn test_java_lint_missing_tool() {
    if check_binary_exists("checkstyle") {
      return;
    }
    let temp = TempDir::new().unwrap();
    std::fs::write(temp.path().join("Main.java"), "class Main {}\n").unwrap();

    let ctx = ExecutionContext {
      root: temp.path().to_path_buf(),
      paths: Vec::new(),
      global_config: ResolvedGlobalConfig::default(),
      lang_config: ResolvedLangConfig::new("java"),
      check_only: false,
    };

    let surface = JavaSurface;
    let res = surface.lint(&ctx, false);
    assert!(matches!(res.status, SurfaceStatus::ToolMissing { .. }));
  }

  #[test]
  fn test_java_format_missing_tool() {
    if check_binary_exists("google-java-format") {
      return;
    }
    let temp = TempDir::new().unwrap();
    std::fs::write(temp.path().join("Main.java"), "class Main {}\n").unwrap();

    let ctx = ExecutionContext {
      root: temp.path().to_path_buf(),
      paths: Vec::new(),
      global_config: ResolvedGlobalConfig::default(),
      lang_config: ResolvedLangConfig::new("java"),
      check_only: false,
    };

    let surface = JavaSurface;
    let res = surface.format(&ctx);
    assert!(matches!(res.status, SurfaceStatus::ToolMissing { .. }));
  }
}
