use super::{
  DeclaresFacets, ExecutionContext, Facet, FacetSupport, LanguageSurface,
  NativeConfig, SurfaceResult, SurfaceStatus, ToolInfo, check_binary_exists,
  create_tool_command, diff_check_via_tempcopy, find_files_with_ext,
  serialize_json_pretty, sync_file_helper, tool_missing_result,
};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::time::Instant;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PrettierConfig {
  pub tab_width: usize,
  pub print_width: usize,
  pub use_tabs: bool,
  pub end_of_line: String,
  pub prose_wrap: String,
}

impl NativeConfig for PrettierConfig {
  const FILE_NAME: &'static str = ".prettierrc.json";
}

impl PrettierConfig {
  #[must_use]
  pub fn from_context(ctx: &ExecutionContext) -> Self {
    let eol = match ctx.global_config.end_of_line.to_lowercase().as_str() {
      "crlf" => "crlf",
      "cr" => "cr",
      _ => "lf",
    };
    let prose_wrap = ctx.lang_config.prose_wrap.as_deref().unwrap_or("always");

    Self {
      tab_width: ctx.lang_config.indent_size,
      print_width: ctx.lang_config.line_length,
      use_tabs: ctx.lang_config.use_tabs,
      end_of_line: eol.to_string(),
      prose_wrap: prose_wrap.to_string(),
    }
  }

  /// Renders the Prettier configuration as a pretty JSON string.
  ///
  /// # Errors
  ///
  /// Returns a [`serde_json::Error`] if serialization fails.
  pub fn render(&self) -> Result<String, serde_json::Error> {
    serialize_json_pretty(self)
  }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MarkdownlintComment {
  pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MarkdownlintMd013 {
  pub line_length: usize,
  pub code_blocks: bool,
  pub tables: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MarkdownlintConfig {
  #[serde(rename = "$comment")]
  pub comment: MarkdownlintComment,
  pub default: bool,
  #[serde(rename = "MD013")]
  pub md013: MarkdownlintMd013,
}

impl NativeConfig for MarkdownlintConfig {
  const FILE_NAME: &'static str = ".markdownlint.json";
}

impl MarkdownlintConfig {
  #[must_use]
  pub fn from_context(ctx: &ExecutionContext) -> Self {
    Self {
      comment: MarkdownlintComment {
        description: "WARNING: DO NOT EDIT THIS FILE DIRECTLY! Automatically generated and managed by formality (fml). Canonical source of truth: formality.toml. Run 'fml sync' to update.".to_string(),
      },
      default: true,
      md013: MarkdownlintMd013 {
        line_length: ctx.lang_config.line_length,
        code_blocks: false,
        tables: false,
      },
    }
  }

  /// Renders the markdownlint configuration as a pretty JSON string.
  ///
  /// # Errors
  ///
  /// Returns a [`serde_json::Error`] if serialization fails.
  pub fn render(&self) -> Result<String, serde_json::Error> {
    serialize_json_pretty(self)
  }
}

#[must_use]
pub fn build_markdownlint_args(
  files: &[PathBuf],
  fix: bool,
  extra_args: &[String],
) -> Vec<String> {
  let mut args = Vec::new();
  if fix {
    args.push("--fix".to_string());
  }
  for f in files {
    args.push(f.to_string_lossy().to_string());
  }
  args.extend(extra_args.iter().cloned());
  args
}

#[must_use]
pub fn build_prettier_fmt_args(
  files: &[PathBuf],
  extra_args: &[String],
) -> Vec<String> {
  let mut args = vec!["--write".to_string()];
  for f in files {
    args.push(f.to_string_lossy().to_string());
  }
  args.extend(extra_args.iter().cloned());
  args
}

#[derive(Debug, Default, Clone, Copy)]
pub struct MarkdownSurface;

impl DeclaresFacets for MarkdownSurface {
  fn facet_support(&self, facet: Facet) -> FacetSupport {
    match facet {
      Facet::IndentTabs
      | Facet::IndentWidth
      | Facet::LineLength
      | Facet::ProseWrap => FacetSupport::Configurable,
      Facet::QuoteStyle
      | Facet::TrailingComma
      | Facet::ImportSort
      | Facet::Edition
      | Facet::Standard => FacetSupport::Unsupported,
    }
  }
}

const MD_EXTENSIONS: &[&str] = &["md", "markdown", "mdown", "mkdn"];

impl LanguageSurface for MarkdownSurface {
  fn name(&self) -> &'static str {
    "markdown"
  }

  fn aliases(&self) -> &[&'static str] {
    &["md"]
  }

  fn file_extensions(&self) -> &[&'static str] {
    MD_EXTENSIONS
  }

  fn clone_box(&self) -> Box<dyn LanguageSurface> {
    Box::new(*self)
  }

  fn supports_lint_fix(&self) -> bool {
    true
  }

  fn detect(&self, root: &Path) -> bool {
    root.join(".markdownlint.json").is_file()
      || root.join(".markdownlint.yaml").is_file()
      || !find_files_with_ext(root, MD_EXTENSIONS, &[], &[], &[]).is_empty()
  }

  fn tool_info(
    &self,
    _config: &crate::config::ResolvedLangConfig,
  ) -> Vec<ToolInfo> {
    vec![
      ToolInfo {
        binary: "prettier",
        description: "Opinionated code/markdown formatter",
        install_hint: "Install via: npm install -g prettier (or pnpm add -g prettier / brew install prettier / winget install Prettier.Prettier)",
        is_required_for_fmt: true,
        is_required_for_lint: false,
      },
      ToolInfo {
        binary: "markdownlint-cli2",
        description: "Fast markdown linter",
        install_hint: "Install via: npm install -g markdownlint-cli2 (or brew install markdownlint-cli2)",
        is_required_for_fmt: false,
        is_required_for_lint: true,
      },
    ]
  }

  // Orchestrates prettier markdown formatting across check and write modes with fallback tempcopy handling.
  #[allow(clippy::too_many_lines)]
  fn format(&self, ctx: &ExecutionContext) -> SurfaceResult {
    let start = Instant::now();

    if !check_binary_exists("prettier") {
      return tool_missing_result(
        self.name(),
        start,
        "prettier",
        "npm install -g prettier",
      );
    }

    let files = find_files_with_ext(
      &ctx.root,
      MD_EXTENSIONS,
      &ctx.paths,
      &ctx.lang_config.files,
      &ctx.lang_config.exclude,
    );
    if files.is_empty() {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      };
    }

    let md_binary = if check_binary_exists("markdownlint-cli2") {
      Some("markdownlint-cli2")
    } else if check_binary_exists("markdownlint") {
      Some("markdownlint")
    } else {
      None
    };

    if ctx.check_only {
      return diff_check_via_tempcopy(
        &files,
        |scratch| {
          if let Some(bin) = md_binary {
            let mut md_cmd = create_tool_command(bin);
            md_cmd.arg("--fix").arg(scratch);
            md_cmd.current_dir(&ctx.root);
            let _ = md_cmd.output();
          }

          let mut cmd = create_tool_command("prettier");
          cmd
            .arg("--write")
            .arg("--parser")
            .arg("markdown")
            .arg(scratch);
          cmd.args(&ctx.lang_config.extra_args);
          cmd.current_dir(&ctx.root);
          cmd.output()
        },
        self.name(),
        start,
      );
    }

    if let Some(bin) = md_binary {
      let mut md_cmd = create_tool_command(bin);
      md_cmd.arg("--fix");
      for f in &files {
        md_cmd.arg(f);
      }
      md_cmd.current_dir(&ctx.root);
      let _ = md_cmd.output();
    }

    let mut cmd = create_tool_command("prettier");
    cmd.args(build_prettier_fmt_args(&files, &ctx.lang_config.extra_args));
    cmd.current_dir(&ctx.root);

    match cmd.output() {
      Ok(output) => {
        if output.status.success() {
          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::Passed,
            duration: start.elapsed(),
          }
        } else {
          let stderr = String::from_utf8_lossy(&output.stderr).to_string();
          let stdout = String::from_utf8_lossy(&output.stdout).to_string();
          let msg = if !stdout.trim().is_empty() {
            stdout
          } else if !stderr.trim().is_empty() {
            stderr
          } else {
            "Markdown formatting violations found".to_string()
          };

          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::ViolationsFound {
              message: msg,
              diff: None,
            },
            duration: start.elapsed(),
          }
        }
      }
      Err(e) => SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to execute prettier: {e}"),
        },
        duration: start.elapsed(),
      },
    }
  }

  fn lint(&self, ctx: &ExecutionContext, fix: bool) -> SurfaceResult {
    let start = Instant::now();

    let binary = if check_binary_exists("markdownlint-cli2") {
      "markdownlint-cli2"
    } else if check_binary_exists("markdownlint") {
      "markdownlint"
    } else {
      return tool_missing_result(
        self.name(),
        start,
        "markdownlint-cli2",
        "npm install -g markdownlint-cli2",
      );
    };

    let files = find_files_with_ext(
      &ctx.root,
      MD_EXTENSIONS,
      &ctx.paths,
      &ctx.lang_config.files,
      &ctx.lang_config.exclude,
    );
    if files.is_empty() {
      return SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::Passed,
        duration: start.elapsed(),
      };
    }

    let mut cmd = create_tool_command(binary);
    cmd.args(build_markdownlint_args(
      &files,
      fix,
      &ctx.lang_config.extra_args,
    ));
    cmd.current_dir(&ctx.root);

    match cmd.output() {
      Ok(output) => {
        if output.status.success() {
          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::Passed,
            duration: start.elapsed(),
          }
        } else {
          let stderr = String::from_utf8_lossy(&output.stderr).to_string();
          let stdout = String::from_utf8_lossy(&output.stdout).to_string();
          let msg = if stderr.trim().is_empty() {
            stdout
          } else {
            stderr
          };

          SurfaceResult {
            surface_name: self.name(),
            status: SurfaceStatus::ViolationsFound {
              message: msg,
              diff: None,
            },
            duration: start.elapsed(),
          }
        }
      }
      Err(e) => SurfaceResult {
        surface_name: self.name(),
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to execute {binary}: {e}"),
        },
        duration: start.elapsed(),
      },
    }
  }

  fn sync_config(&self, ctx: &ExecutionContext, check: bool) -> SurfaceResult {
    let start = Instant::now();
    let target = ctx.root.join(MarkdownlintConfig::FILE_NAME);
    let md_cfg = MarkdownlintConfig::from_context(ctx);
    let content = match md_cfg.render() {
      Ok(c) => c,
      Err(e) => {
        return SurfaceResult {
          surface_name: self.name(),
          status: SurfaceStatus::ExecutionError {
            message: format!(
              "Failed to serialize {}: {}",
              MarkdownlintConfig::FILE_NAME,
              e
            ),
          },
          duration: start.elapsed(),
        };
      }
    };

    let md_res = sync_file_helper(
      &target,
      MarkdownlintConfig::FILE_NAME,
      &content,
      check,
      start,
      self.name(),
    );
    if !md_res.is_success() {
      return md_res;
    }

    // Also sync .prettierrc.json
    sync_prettier_config(ctx, check, start, self.name())
  }
}

#[must_use]
pub fn sync_prettier_config(
  ctx: &ExecutionContext,
  check: bool,
  start: Instant,
  surface_name: &'static str,
) -> SurfaceResult {
  let target = ctx.root.join(PrettierConfig::FILE_NAME);
  let prettier_cfg = PrettierConfig::from_context(ctx);
  let content = match prettier_cfg.render() {
    Ok(c) => c,
    Err(e) => {
      return SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!(
            "Failed to serialize {}: {}",
            PrettierConfig::FILE_NAME,
            e
          ),
        },
        duration: start.elapsed(),
      };
    }
  };

  sync_file_helper(
    &target,
    PrettierConfig::FILE_NAME,
    &content,
    check,
    start,
    surface_name,
  )
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::{ResolvedGlobalConfig, ResolvedLangConfig};
  use std::sync::Arc;
  use tempfile::TempDir;

  #[test]
  fn test_prettier_config_typed_serialization() {
    let cfg = PrettierConfig {
      tab_width: 4,
      print_width: 100,
      use_tabs: true,
      end_of_line: "crlf".to_string(),
      prose_wrap: "preserve".to_string(),
    };
    let rendered = cfg.render().unwrap();
    assert!(!rendered.contains("$comment"));
    assert!(rendered.contains("\"tabWidth\": 4"));
    assert!(rendered.contains("\"printWidth\": 100"));
    assert!(rendered.contains("\"useTabs\": true"));
    assert!(rendered.contains("\"endOfLine\": \"crlf\""));
    assert!(rendered.contains("\"proseWrap\": \"preserve\""));
  }

  #[test]
  fn test_markdownlint_config_typed_serialization() {
    let cfg = MarkdownlintConfig {
      comment: MarkdownlintComment {
        description: "desc".to_string(),
      },
      default: true,
      md013: MarkdownlintMd013 {
        line_length: 120,
        code_blocks: false,
        tables: false,
      },
    };
    let rendered = cfg.render().unwrap();
    assert!(rendered.contains("\"$comment\":"));
    assert!(rendered.contains("\"description\": \"desc\""));
    assert!(rendered.contains("\"default\": true"));
    assert!(rendered.contains("\"MD013\":"));
    assert!(rendered.contains("\"line_length\": 120"));
  }

  #[test]
  fn test_markdown_supports_lint_fix() {
    assert!(MarkdownSurface.supports_lint_fix());
  }

  #[test]
  fn test_build_markdownlint_args_with_and_without_fix() {
    let no_fix = build_markdownlint_args(&[], false, &[]);
    assert_eq!(no_fix, Vec::<String>::new());

    let files = vec![PathBuf::from("a.md"), PathBuf::from("b.md")];
    let extra = vec!["--config".to_string(), ".custom-mdl.json".to_string()];
    let with_fix = build_markdownlint_args(&files, true, &extra);
    assert_eq!(
      with_fix,
      vec![
        "--fix".to_string(),
        "a.md".to_string(),
        "b.md".to_string(),
        "--config".to_string(),
        ".custom-mdl.json".to_string(),
      ]
    );
  }

  #[test]
  fn test_build_prettier_fmt_args() {
    let files = vec![PathBuf::from("readme.md")];
    let extra = vec!["--loglevel".to_string(), "warn".to_string()];
    let args = build_prettier_fmt_args(&files, &extra);
    assert_eq!(
      args,
      vec![
        "--write".to_string(),
        "readme.md".to_string(),
        "--loglevel".to_string(),
        "warn".to_string(),
      ]
    );
  }

  #[test]
  fn test_markdown_sync_config() {
    let temp = TempDir::new().unwrap();
    let surface = MarkdownSurface;
    let mut lang_cfg = ResolvedLangConfig::new("markdown");
    lang_cfg.line_length = 100;
    lang_cfg.indent_size = 2;

    let ctx = ExecutionContext {
      root: temp.path().to_path_buf(),
      paths: Arc::new(Vec::new()),
      global_config: Arc::new(ResolvedGlobalConfig::default()),
      lang_config: lang_cfg,
      check_only: false,
    };

    let res = surface.sync_config(&ctx, false);
    assert!(matches!(
      res.status,
      SurfaceStatus::ConfigSynced { created: true, .. }
    ));

    let md_path = temp.path().join(".markdownlint.json");
    let prettier_path = temp.path().join(".prettierrc.json");
    assert!(md_path.is_file());
    assert!(prettier_path.is_file());

    let md_content = std::fs::read_to_string(&md_path).unwrap();
    let prettier_content = std::fs::read_to_string(&prettier_path).unwrap();

    assert!(md_content.contains("\"line_length\": 100"));
    assert!(prettier_content.contains("\"printWidth\": 100"));
    assert!(!prettier_content.contains("$comment"));
  }
}
