pub use crate::editorconfig::{
  EDITORCONFIG_FILE_NAME, generate_editorconfig,
  generate_editorconfig_from_config, sync_editorconfig,
};
use crate::surfaces::{
  ExecutionContext, SurfaceResult, SurfaceStatus, sync_file_helper,
};
use serde::Serialize;
use std::time::Instant;

pub const AUTO_GENERATED_HEADER: &str = "# Auto-generated by formality. DO NOT EDIT.\n# Changes to this file may be overwritten. Configure formality.toml instead.\n\n";

/// Trait implemented by typed configurations that target a specific native tool configuration file.
pub trait NativeConfig: Sized {
  /// The file name of the native configuration file (e.g., `ruff.toml`, `.golangci.yml`, `checkstyle.xml`).
  const FILE_NAME: &'static str;

  /// Constructs the typed configuration struct from an [`ExecutionContext`].
  fn from_context(ctx: &ExecutionContext) -> Self;

  /// Renders the configuration to its final string representation.
  ///
  /// # Errors
  ///
  /// Returns an error string if the underlying serialization (TOML, YAML, or
  /// JSON, depending on the implementor) fails.
  fn render(&self) -> Result<String, String>;
}

/// Serializes a struct to TOML and prepends the standard formality auto-generated warning header.
///
/// # Errors
///
/// Returns a [`toml::ser::Error`] if serialization fails.
pub fn serialize_toml_with_header<T: Serialize>(
  val: &T,
) -> Result<String, toml::ser::Error> {
  let toml_str = toml::to_string_pretty(val)?;
  Ok(format!("{AUTO_GENERATED_HEADER}{toml_str}"))
}

/// Serializes a struct to YAML and prepends the standard formality auto-generated warning header.
///
/// # Errors
///
/// Returns a [`serde_yaml::Error`] if serialization fails.
pub fn serialize_yaml_with_header<T: Serialize>(
  val: &T,
) -> Result<String, serde_yaml::Error> {
  let yaml_str = serde_yaml::to_string(val)?;
  let body = if let Some(stripped) = yaml_str.strip_prefix("---\n") {
    format!("---\n{stripped}")
  } else {
    yaml_str
  };
  Ok(format!("{AUTO_GENERATED_HEADER}{body}"))
}

/// Serializes a struct to pretty-formatted JSON with trailing newline.
///
/// # Errors
///
/// Returns a [`serde_json::Error`] if serialization fails.
pub fn serialize_json_pretty<T: Serialize>(
  val: &T,
) -> Result<String, serde_json::Error> {
  let mut json_str = serde_json::to_string_pretty(val)?;
  if !json_str.ends_with('\n') {
    json_str.push('\n');
  }
  Ok(json_str)
}

/// Helper to render a serializable native config struct to string based on its file extension.
///
/// Dispatches based on [`NativeConfig::FILE_NAME`]:
/// - `.json` -> [`serialize_json_pretty`]
/// - `.yaml`, `.yml`, or containing `"clang"` -> [`serialize_yaml_with_header`]
/// - `.toml` or default -> [`serialize_toml_with_header`]
///
/// # Errors
///
/// Returns an error string if JSON, YAML, or TOML serialization fails.
// Native tool configuration filenames (e.g. .golangci.yml, .clang-format) are fixed static ASCII strings.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
pub fn render_native_config<T: Serialize + NativeConfig>(
  cfg: &T,
) -> Result<String, String> {
  if T::FILE_NAME.ends_with(".json") {
    serialize_json_pretty(cfg).map_err(|e| e.to_string())
  } else if T::FILE_NAME.ends_with(".yaml")
    || T::FILE_NAME.ends_with(".yml")
    || T::FILE_NAME.contains("clang")
  {
    serialize_yaml_with_header(cfg).map_err(|e| e.to_string())
  } else {
    serialize_toml_with_header(cfg).map_err(|e| e.to_string())
  }
}

/// Helper to sync a typed [`NativeConfig`] to disk for a surface.
///
/// Automatically creates the config via `C::from_context(ctx)`, renders it via
/// `cfg.render()`, and invokes [`sync_file_helper`].
#[must_use]
pub fn sync_native_config<C: NativeConfig>(
  ctx: &ExecutionContext,
  check: bool,
  start: Instant,
  surface_name: &'static str,
) -> SurfaceResult {
  let target = ctx.root.join(C::FILE_NAME);
  let cfg = C::from_context(ctx);
  let content = match cfg.render() {
    Ok(c) => c,
    Err(e) => {
      return SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to serialize {}: {}", C::FILE_NAME, e),
        },
        duration: start.elapsed(),
      };
    }
  };

  sync_file_helper(&target, C::FILE_NAME, &content, check, start, surface_name)
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::{ResolvedGlobalConfig, ResolvedLangConfig};
  use serde::{Deserialize, Serialize};
  use std::sync::Arc;
  use tempfile::TempDir;

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyTomlConfig {
    indent_size: usize,
    use_tabs: bool,
  }

  impl NativeConfig for DummyTomlConfig {
    const FILE_NAME: &'static str = "dummy.toml";

    fn from_context(ctx: &ExecutionContext) -> Self {
      Self {
        indent_size: ctx.lang_config.indent_size,
        use_tabs: ctx.lang_config.use_tabs,
      }
    }

    fn render(&self) -> Result<String, String> {
      render_native_config(self)
    }
  }

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyYamlConfig {
    rules: Vec<String>,
  }

  impl NativeConfig for DummyYamlConfig {
    const FILE_NAME: &'static str = "dummy.yaml";

    fn from_context(_ctx: &ExecutionContext) -> Self {
      Self {
        rules: vec![
          "line-length".to_string(),
          "no-trailing-spaces".to_string(),
        ],
      }
    }

    fn render(&self) -> Result<String, String> {
      render_native_config(self)
    }
  }

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyJsonConfig {
    tab_width: usize,
  }

  impl NativeConfig for DummyJsonConfig {
    const FILE_NAME: &'static str = "dummy.json";

    fn from_context(ctx: &ExecutionContext) -> Self {
      Self {
        tab_width: ctx.lang_config.indent_size,
      }
    }

    fn render(&self) -> Result<String, String> {
      render_native_config(self)
    }
  }

  #[test]
  fn test_serialize_toml_with_header() {
    let cfg = DummyTomlConfig {
      indent_size: 4,
      use_tabs: false,
    };
    let output = serialize_toml_with_header(&cfg).unwrap();
    assert!(output.starts_with(AUTO_GENERATED_HEADER));
    assert!(output.contains("indent_size = 4"));
    assert!(output.contains("use_tabs = false"));
  }

  #[test]
  fn test_serialize_yaml_with_header() {
    let cfg = DummyYamlConfig {
      rules: vec!["line-length".to_string(), "no-trailing-spaces".to_string()],
    };
    let output = serialize_yaml_with_header(&cfg).unwrap();
    assert!(output.starts_with(AUTO_GENERATED_HEADER));
    assert!(output.contains("line-length"));
    assert!(output.contains("no-trailing-spaces"));
  }

  #[test]
  fn test_serialize_json_pretty() {
    let cfg = DummyJsonConfig { tab_width: 2 };
    let output = serialize_json_pretty(&cfg).unwrap();
    assert!(output.contains("\"tab_width\": 2"));
    assert!(output.ends_with('\n'));
  }

  #[test]
  fn test_render_native_config_dispatch() {
    let toml_cfg = DummyTomlConfig {
      indent_size: 2,
      use_tabs: true,
    };
    let toml_out = render_native_config(&toml_cfg).unwrap();
    assert!(toml_out.starts_with(AUTO_GENERATED_HEADER));
    assert!(toml_out.contains("indent_size = 2"));

    let yaml_cfg = DummyYamlConfig {
      rules: vec!["rule1".to_string()],
    };
    let yaml_out = render_native_config(&yaml_cfg).unwrap();
    assert!(yaml_out.starts_with(AUTO_GENERATED_HEADER));
    assert!(yaml_out.contains("rule1"));

    let json_cfg = DummyJsonConfig { tab_width: 4 };
    let json_out = render_native_config(&json_cfg).unwrap();
    assert!(json_out.contains("\"tab_width\": 4"));
  }

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyClangConfig {
    based_on_style: String,
  }

  impl NativeConfig for DummyClangConfig {
    const FILE_NAME: &'static str = ".clang-format";

    fn from_context(_ctx: &ExecutionContext) -> Self {
      Self {
        based_on_style: "Google".to_string(),
      }
    }

    fn render(&self) -> Result<String, String> {
      render_native_config(self)
    }
  }

  #[test]
  fn test_render_native_config_clang_filename_dispatches_to_yaml() {
    let cfg = DummyClangConfig {
      based_on_style: "Google".to_string(),
    };
    let out = render_native_config(&cfg).unwrap();
    assert!(out.starts_with(AUTO_GENERATED_HEADER));
    // YAML rendering uses `key: value`, not TOML's `key = value`.
    assert!(out.contains("based_on_style: Google"));
    assert!(!out.contains("based_on_style = "));
  }

  #[test]
  fn test_serialize_yaml_with_header_strips_leading_document_marker() {
    let cfg = DummyYamlConfig {
      rules: vec!["x".to_string()],
    };
    let output = serialize_yaml_with_header(&cfg).unwrap();
    assert!(output.starts_with(AUTO_GENERATED_HEADER));
    assert!(output.matches("---").count() <= 1);
  }

  #[test]
  fn test_sync_native_config_helper() {
    let temp = TempDir::new().unwrap();
    let mut lang_config = ResolvedLangConfig::new("dummy");
    lang_config.indent_size = 4;
    lang_config.use_tabs = false;

    let ctx = ExecutionContext {
      root: temp.path().to_path_buf(),
      paths: Arc::new(Vec::new()),
      global_config: Arc::new(ResolvedGlobalConfig::default()),
      lang_config,
      check_only: false,
    };

    let start = Instant::now();
    let res =
      sync_native_config::<DummyTomlConfig>(&ctx, false, start, "dummy");
    assert!(res.is_success());
    let written =
      std::fs::read_to_string(temp.path().join("dummy.toml")).unwrap();
    assert!(written.contains("indent_size = 4"));

    let check_res =
      sync_native_config::<DummyTomlConfig>(&ctx, true, start, "dummy");
    assert!(check_res.is_success());
  }
}
