pub use crate::editorconfig::{
  EDITORCONFIG_FILE_NAME, generate_editorconfig,
  generate_editorconfig_from_config, sync_editorconfig,
};
use serde::Serialize;

pub const AUTO_GENERATED_HEADER: &str = "# Auto-generated by formality. DO NOT EDIT.\n# Changes to this file may be overwritten. Configure formality.toml instead.\n\n";

/// Trait implemented by typed configurations that target a specific native tool configuration file.
pub trait NativeConfig: Serialize {
  const FILE_NAME: &'static str;
}

/// Serializes a struct to TOML and prepends the standard formality auto-generated warning header.
pub fn serialize_toml_with_header<T: Serialize>(
  val: &T,
) -> Result<String, toml::ser::Error> {
  let toml_str = toml::to_string_pretty(val)?;
  Ok(format!("{AUTO_GENERATED_HEADER}{toml_str}"))
}

/// Serializes a struct to YAML and prepends the standard formality auto-generated warning header.
pub fn serialize_yaml_with_header<T: Serialize>(
  val: &T,
) -> Result<String, serde_yaml::Error> {
  let yaml_str = serde_yaml::to_string(val)?;
  let body = if let Some(stripped) = yaml_str.strip_prefix("---\n") {
    format!("---\n{stripped}")
  } else {
    yaml_str
  };
  Ok(format!("{AUTO_GENERATED_HEADER}{body}"))
}

/// Serializes a struct to pretty-formatted JSON with trailing newline.
pub fn serialize_json_pretty<T: Serialize>(
  val: &T,
) -> Result<String, serde_json::Error> {
  let mut json_str = serde_json::to_string_pretty(val)?;
  if !json_str.ends_with('\n') {
    json_str.push('\n');
  }
  Ok(json_str)
}

/// Helper to render a native config struct to string based on format preference and file extension.
pub fn render_native_config<T: NativeConfig>(
  cfg: &T,
  as_json: bool,
) -> Result<String, String> {
  if as_json {
    serialize_json_pretty(cfg).map_err(|e| e.to_string())
  } else if T::FILE_NAME.ends_with(".yaml")
    || T::FILE_NAME.ends_with(".yml")
    || T::FILE_NAME.contains("clang")
  {
    serialize_yaml_with_header(cfg).map_err(|e| e.to_string())
  } else {
    serialize_toml_with_header(cfg).map_err(|e| e.to_string())
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use serde::{Deserialize, Serialize};

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyTomlConfig {
    indent_size: usize,
    use_tabs: bool,
  }

  impl NativeConfig for DummyTomlConfig {
    const FILE_NAME: &'static str = "dummy.toml";
  }

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyYamlConfig {
    rules: Vec<String>,
  }

  impl NativeConfig for DummyYamlConfig {
    const FILE_NAME: &'static str = "dummy.yaml";
  }

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyJsonConfig {
    tab_width: usize,
  }

  impl NativeConfig for DummyJsonConfig {
    const FILE_NAME: &'static str = "dummy.json";
  }

  #[test]
  fn test_serialize_toml_with_header() {
    let cfg = DummyTomlConfig {
      indent_size: 4,
      use_tabs: false,
    };
    let output = serialize_toml_with_header(&cfg).unwrap();
    assert!(output.starts_with(AUTO_GENERATED_HEADER));
    assert!(output.contains("indent_size = 4"));
    assert!(output.contains("use_tabs = false"));
  }

  #[test]
  fn test_serialize_yaml_with_header() {
    let cfg = DummyYamlConfig {
      rules: vec!["line-length".to_string(), "no-trailing-spaces".to_string()],
    };
    let output = serialize_yaml_with_header(&cfg).unwrap();
    assert!(output.starts_with(AUTO_GENERATED_HEADER));
    assert!(output.contains("line-length"));
    assert!(output.contains("no-trailing-spaces"));
  }

  #[test]
  fn test_serialize_json_pretty() {
    let cfg = DummyJsonConfig { tab_width: 2 };
    let output = serialize_json_pretty(&cfg).unwrap();
    assert!(output.contains("\"tab_width\": 2"));
    assert!(output.ends_with('\n'));
  }

  #[test]
  fn test_render_native_config_dispatch() {
    let toml_cfg = DummyTomlConfig {
      indent_size: 2,
      use_tabs: true,
    };
    let toml_out = render_native_config(&toml_cfg, false).unwrap();
    assert!(toml_out.starts_with(AUTO_GENERATED_HEADER));
    assert!(toml_out.contains("indent_size = 2"));

    let yaml_cfg = DummyYamlConfig {
      rules: vec!["rule1".to_string()],
    };
    let yaml_out = render_native_config(&yaml_cfg, false).unwrap();
    assert!(yaml_out.starts_with(AUTO_GENERATED_HEADER));
    assert!(yaml_out.contains("rule1"));

    let json_cfg = DummyJsonConfig { tab_width: 4 };
    let json_out = render_native_config(&json_cfg, true).unwrap();
    assert!(json_out.contains("\"tab_width\": 4"));
  }

  #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
  struct DummyClangConfig {
    based_on_style: String,
  }

  impl NativeConfig for DummyClangConfig {
    // .clang-format/.clang-tidy carry no .yaml/.yml extension at all, yet
    // are YAML-formatted files — render_native_config special-cases any
    // FILE_NAME containing "clang" to dispatch to the YAML serializer
    // rather than falling through to the TOML default. This branch had no
    // test coverage at all.
    const FILE_NAME: &'static str = ".clang-format";
  }

  #[test]
  fn test_render_native_config_clang_filename_dispatches_to_yaml() {
    let cfg = DummyClangConfig {
      based_on_style: "Google".to_string(),
    };
    let out = render_native_config(&cfg, false).unwrap();
    assert!(out.starts_with(AUTO_GENERATED_HEADER));
    // YAML rendering uses `key: value`, not TOML's `key = value`.
    assert!(out.contains("based_on_style: Google"));
    assert!(!out.contains("based_on_style = "));
  }

  #[test]
  fn test_serialize_yaml_with_header_strips_leading_document_marker() {
    // serde_yaml prefixes output with a `---` document marker; strip_prefix
    // + reformat must fold the header in ahead of it rather than leaving
    // a bare `---` line floating before the AUTO_GENERATED_HEADER comment.
    let cfg = DummyYamlConfig {
      rules: vec!["x".to_string()],
    };
    let output = serialize_yaml_with_header(&cfg).unwrap();
    // The header comment must come first, and there must be at most one
    // "---" document marker line if serde_yaml emits one at all — the
    // point of the strip_prefix logic is to avoid ever emitting the marker
    // sandwiched *between* two copies of the header content.
    assert!(output.starts_with(AUTO_GENERATED_HEADER));
    assert!(output.matches("---").count() <= 1);
  }
}
