use super::*;
use crate::surfaces::SurfaceStatus;
use tempfile::TempDir;

fn create_dummy_success_output() -> std::process::Output {
  #[cfg(windows)]
  {
    std::process::Command::new("cmd")
      .args(["/C", "exit 0"])
      .output()
      .expect("cmd exit 0 failed")
  }
  #[cfg(not(windows))]
  {
    std::process::Command::new("true")
      .output()
      .expect("true failed")
  }
}

#[test]
fn test_is_auto_generated_recognizes_all_header_variants() {
  // is_auto_generated is the guard that decides whether fml is allowed to
  // silently overwrite an existing config file. It had zero test coverage
  // despite gating the ManualConfig-vs-ConfigSynced branch entirely.
  assert!(is_auto_generated("# DO NOT EDIT this generated file\n..."));
  assert!(is_auto_generated("// Auto-generated by formality\nfoo = 1"));
  assert!(is_auto_generated(
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nfoo = 1"
  ));
  assert!(!is_auto_generated("foo = 1\nbar = 2\n"));
  assert!(!is_auto_generated(""));
}

#[test]
fn test_sync_file_helper_creates_missing_file() {
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  let start = Instant::now();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    false,
    start,
    "rust",
  );

  assert!(matches!(
    res.status,
    SurfaceStatus::ConfigSynced { created: true, .. }
  ));
  assert!(path.is_file());
  assert_eq!(
    std::fs::read_to_string(&path).unwrap(),
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n"
  );
}

#[test]
fn test_sync_file_helper_matching_content_is_passed() {
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  // Trailing whitespace differences must not count as drift (comparison is
  // trim()'d on both sides).
  std::fs::write(&path, "max_width = 80\n\n  ").unwrap();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "max_width = 80",
    false,
    Instant::now(),
    "rust",
  );
  assert!(matches!(res.status, SurfaceStatus::Passed));
}

#[test]
fn test_sync_file_helper_auto_generated_drift_is_overwritten() {
  // A file previously written by fml (carries the header) that has since
  // drifted from the expected content must be silently rewritten in
  // non-check mode — the manual-config protection must NOT trigger here.
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  std::fs::write(
    &path,
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 100\n",
  )
  .unwrap();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    false,
    Instant::now(),
    "rust",
  );

  assert!(matches!(
    res.status,
    SurfaceStatus::ConfigSynced { created: false, .. }
  ));
  assert!(
    std::fs::read_to_string(&path)
      .unwrap()
      .contains("max_width = 80")
  );
}

#[test]
fn test_sync_file_helper_auto_generated_drift_check_mode_reports_diff() {
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  std::fs::write(
    &path,
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 100\n",
  )
  .unwrap();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    true,
    Instant::now(),
    "rust",
  );

  match res.status {
    SurfaceStatus::ConfigDrifted { file, diff } => {
      assert_eq!(file, ".rustfmt.toml");
      assert!(diff.contains("max_width"));
    }
    other => panic!("expected ConfigDrifted, got {other:?}"),
  }
  // check mode must never write to disk.
  assert!(
    std::fs::read_to_string(&path)
      .unwrap()
      .contains("max_width = 100")
  );
}

#[test]
fn test_sync_file_helper_manual_file_is_protected_from_overwrite() {
  // A hand-written config with no fml header must never be silently
  // clobbered, in either check or write mode — this is the exact
  // protection this project's own pre-commit hook (.githooks/pre-commit,
  // `fml sync --check`) relies on to avoid destroying user settings.
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  std::fs::write(&path, "max_width = 120\n# hand-tuned, no header\n").unwrap();

  let res_write = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    false,
    Instant::now(),
    "rust",
  );
  match res_write.status {
    SurfaceStatus::ManualConfig { file, suggestion } => {
      assert_eq!(file, ".rustfmt.toml");
      assert!(suggestion.contains("was not generated by formality"));
      assert!(suggestion.contains("max_width = 80"));
    }
    other => panic!("expected ManualConfig, got {other:?}"),
  }
  // The file on disk must be untouched.
  assert_eq!(
    std::fs::read_to_string(&path).unwrap(),
    "max_width = 120\n# hand-tuned, no header\n"
  );

  let res_check = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    true,
    Instant::now(),
    "rust",
  );
  assert!(matches!(
    res_check.status,
    SurfaceStatus::ManualConfig { .. }
  ));
}

#[test]
fn test_sync_file_helper_prettierrc_valid_json_without_header_is_not_manual() {
  // Special case: an existing .prettierrc.json with no fml header is still
  // treated as fml-manageable (not "manual") as long as it parses as a
  // valid PrettierConfig shape — this lets fml adopt a prettier config a
  // user hand-wrote in the exact shape fml itself would generate, rather
  // than perpetually flagging it as a foreign file.
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".prettierrc.json");
  std::fs::write(
    &path,
    r#"{"tabWidth":2,"printWidth":80,"useTabs":false,"endOfLine":"lf","proseWrap":"preserve"}"#,
  )
  .unwrap();

  let expected = r#"{
  "tabWidth": 4,
  "printWidth": 100,
  "useTabs": false,
  "endOfLine": "lf",
  "proseWrap": "preserve"
}"#;

  let res = sync_file_helper(
    &path,
    ".prettierrc.json",
    expected,
    false,
    Instant::now(),
    "markdown",
  );
  // Must not be ManualConfig — it should proceed to overwrite instead.
  assert!(matches!(
    res.status,
    SurfaceStatus::ConfigSynced { created: false, .. }
  ));
}

#[test]
fn test_diff_check_via_tempcopy_clean() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("clean.rs");
  std::fs::write(&file, "fn main() {\n  println!(\"clean\");\n}\n").unwrap();

  let start = Instant::now();
  let res = diff_check_via_tempcopy(
    std::slice::from_ref(&file),
    |_scratch| Ok(create_dummy_success_output()),
    "rust",
    start,
  );

  assert!(matches!(res.status, SurfaceStatus::Passed));

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_with_diff() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("dirty.rs");
  std::fs::write(&file, "fn main() {let x=1;}").unwrap();

  let start = Instant::now();
  let res = diff_check_via_tempcopy(
    std::slice::from_ref(&file),
    |scratch| {
      std::fs::write(scratch, "fn main() {\n  let x = 1;\n}\n")?;
      Ok(create_dummy_success_output())
    },
    "rust",
    start,
  );

  match res.status {
    SurfaceStatus::ViolationsFound { message, diff } => {
      assert!(message.is_empty());
      let diff_str = diff.expect("diff should be present");
      assert!(diff_str.contains("dirty.rs"));
      assert!(diff_str.contains("(formatted)"));
    }
    other => panic!("Expected ViolationsFound, got {other:?}"),
  }

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_raii_cleanup_on_error() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("error_case.rs");
  std::fs::write(&file, "invalid syntax").unwrap();

  let start = Instant::now();
  let res = diff_check_via_tempcopy(
    std::slice::from_ref(&file),
    |_scratch| Err(std::io::Error::other("mock execution error")),
    "rust",
    start,
  );

  assert!(matches!(res.status, SurfaceStatus::ExecutionError { .. }));

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_raii_cleanup_on_panic() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("panic_case.rs");
  std::fs::write(&file, "panic content").unwrap();

  let start = Instant::now();
  let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
    diff_check_via_tempcopy(
      std::slice::from_ref(&file),
      |_scratch| {
        panic!("simulated panic inside run_in_place");
      },
      "rust",
      start,
    );
  }));

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}
