use super::*;
use crate::surfaces::SurfaceStatus;
use tempfile::TempDir;

fn create_dummy_success_output() -> std::process::Output {
  #[cfg(windows)]
  {
    std::process::Command::new("cmd")
      .args(["/C", "exit 0"])
      .output()
      .expect("cmd exit 0 failed")
  }
  #[cfg(not(windows))]
  {
    std::process::Command::new("true")
      .output()
      .expect("true failed")
  }
}

#[test]
fn test_is_auto_generated_recognizes_all_header_variants() {
  // is_auto_generated is the guard that decides whether fml is allowed to
  // silently overwrite an existing config file. It had zero test coverage
  // despite gating the ManualConfig-vs-ConfigSynced branch entirely.
  assert!(is_auto_generated("# DO NOT EDIT this generated file\n..."));
  assert!(is_auto_generated("// Auto-generated by formality\nfoo = 1"));
  assert!(is_auto_generated(
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nfoo = 1"
  ));
  assert!(!is_auto_generated("foo = 1\nbar = 2\n"));
  assert!(!is_auto_generated(""));
}

#[test]
fn test_sync_file_helper_creates_missing_file() {
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  let start = Instant::now();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    false,
    start,
    "rust",
  );

  assert!(matches!(
    res.status,
    SurfaceStatus::ConfigSynced { created: true, .. }
  ));
  assert!(path.is_file());
  assert_eq!(
    std::fs::read_to_string(&path).unwrap(),
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n"
  );
}

#[test]
fn test_sync_file_helper_matching_content_is_passed() {
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  // Trailing whitespace differences must not count as drift (comparison is
  // trim()'d on both sides).
  std::fs::write(&path, "max_width = 80\n\n  ").unwrap();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "max_width = 80",
    false,
    Instant::now(),
    "rust",
  );
  assert!(matches!(res.status, SurfaceStatus::Passed));
}

#[test]
fn test_sync_file_helper_auto_generated_drift_is_overwritten() {
  // A file previously written by fml (carries the header) that has since
  // drifted from the expected content must be silently rewritten in
  // non-check mode — the manual-config protection must NOT trigger here.
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  std::fs::write(
    &path,
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 100\n",
  )
  .unwrap();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    false,
    Instant::now(),
    "rust",
  );

  assert!(matches!(
    res.status,
    SurfaceStatus::ConfigSynced { created: false, .. }
  ));
  assert!(
    std::fs::read_to_string(&path)
      .unwrap()
      .contains("max_width = 80")
  );
}

#[test]
fn test_sync_file_helper_auto_generated_drift_check_mode_reports_diff() {
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  std::fs::write(
    &path,
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 100\n",
  )
  .unwrap();

  let res = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    true,
    Instant::now(),
    "rust",
  );

  match res.status {
    SurfaceStatus::ConfigDrifted { file, diff } => {
      assert_eq!(file, ".rustfmt.toml");
      assert!(diff.contains("max_width"));
    }
    other => panic!("expected ConfigDrifted, got {other:?}"),
  }
  // check mode must never write to disk.
  assert!(
    std::fs::read_to_string(&path)
      .unwrap()
      .contains("max_width = 100")
  );
}

#[test]
fn test_sync_file_helper_manual_file_is_protected_from_overwrite() {
  // A hand-written config with no fml header must never be silently
  // clobbered, in either check or write mode — this is the exact
  // protection this project's own pre-commit hook (.githooks/pre-commit,
  // `fml sync --check`) relies on to avoid destroying user settings.
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".rustfmt.toml");
  std::fs::write(&path, "max_width = 120\n# hand-tuned, no header\n").unwrap();

  let res_write = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    false,
    Instant::now(),
    "rust",
  );
  match res_write.status {
    SurfaceStatus::ManualConfig { file, suggestion } => {
      assert_eq!(file, ".rustfmt.toml");
      assert!(suggestion.contains("was not generated by formality"));
      assert!(suggestion.contains("max_width = 80"));
    }
    other => panic!("expected ManualConfig, got {other:?}"),
  }
  // The file on disk must be untouched.
  assert_eq!(
    std::fs::read_to_string(&path).unwrap(),
    "max_width = 120\n# hand-tuned, no header\n"
  );

  let res_check = sync_file_helper(
    &path,
    ".rustfmt.toml",
    "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
    true,
    Instant::now(),
    "rust",
  );
  assert!(matches!(
    res_check.status,
    SurfaceStatus::ManualConfig { .. }
  ));
}

#[test]
fn test_sync_file_helper_json_without_header_is_protected_as_manual() {
  // Hand-written JSON configs (e.g. .prettierrc.json, biome.json) with no fml header
  // or $comment must be protected from silent overwrite.
  let temp = TempDir::new().unwrap();
  let path = temp.path().join(".prettierrc.json");
  std::fs::write(
    &path,
    r#"{"tabWidth":2,"printWidth":80,"useTabs":false,"endOfLine":"lf","proseWrap":"preserve"}"#,
  )
  .unwrap();

  let expected = r#"{
  "$comment": "WARNING: DO NOT EDIT THIS FILE DIRECTLY!",
  "tabWidth": 4,
  "printWidth": 100,
  "useTabs": false,
  "endOfLine": "lf",
  "proseWrap": "preserve"
}"#;

  let res = sync_file_helper(
    &path,
    ".prettierrc.json",
    expected,
    false,
    Instant::now(),
    "markdown",
  );
  assert!(matches!(
    res.status,
    SurfaceStatus::ManualConfig { file, .. } if file == ".prettierrc.json"
  ));

  let biome_path = temp.path().join("biome.json");
  std::fs::write(&biome_path, r#"{"invalidKey": 123}"#).unwrap();

  let res_biome = sync_file_helper(
    &biome_path,
    "biome.json",
    expected,
    false,
    Instant::now(),
    "javascript",
  );
  assert!(matches!(
    res_biome.status,
    SurfaceStatus::ManualConfig { file, .. } if file == "biome.json"
  ));
}

#[test]
fn test_diff_check_via_tempcopy_clean() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("clean.rs");
  std::fs::write(&file, "fn main() {\n  println!(\"clean\");\n}\n").unwrap();

  let start = Instant::now();
  let res = diff_check_via_tempcopy(
    std::slice::from_ref(&file),
    |_scratch| Ok(create_dummy_success_output()),
    "rust",
    start,
  );

  assert!(matches!(res.status, SurfaceStatus::Passed));

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_with_diff() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("dirty.rs");
  std::fs::write(&file, "fn main() {let x=1;}").unwrap();

  let start = Instant::now();
  let res = diff_check_via_tempcopy(
    std::slice::from_ref(&file),
    |scratch| {
      std::fs::write(scratch, "fn main() {\n  let x = 1;\n}\n")?;
      Ok(create_dummy_success_output())
    },
    "rust",
    start,
  );

  match res.status {
    SurfaceStatus::ViolationsFound { message, diff } => {
      assert!(message.is_empty());
      let diff_str = diff.expect("diff should be present");
      assert!(diff_str.contains("dirty.rs"));
      assert!(diff_str.contains("(formatted)"));
    }
    other => panic!("Expected ViolationsFound, got {other:?}"),
  }

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_raii_cleanup_on_error() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("error_case.rs");
  std::fs::write(&file, "invalid syntax").unwrap();

  let start = Instant::now();
  let res = diff_check_via_tempcopy(
    std::slice::from_ref(&file),
    |_scratch| Err(std::io::Error::other("mock execution error")),
    "rust",
    start,
  );

  assert!(matches!(res.status, SurfaceStatus::ExecutionError { .. }));

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_raii_cleanup_on_panic() {
  let temp = TempDir::new().unwrap();
  let file = temp.path().join("panic_case.rs");
  std::fs::write(&file, "panic content").unwrap();

  let start = Instant::now();
  let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
    diff_check_via_tempcopy(
      std::slice::from_ref(&file),
      |_scratch| {
        panic!("simulated panic inside run_in_place");
      },
      "rust",
      start,
    );
  }));

  let ext = file.extension().unwrap().to_str().unwrap();
  let file_stem = file.file_stem().unwrap().to_str().unwrap();
  let scratch = file.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"));
  assert!(!scratch.exists());
}

#[test]
fn test_diff_check_via_tempcopy_naming_and_path_edge_cases() {
  let temp = TempDir::new().unwrap();

  // Case A: File with no extension (e.g., Makefile)
  let no_ext = temp.path().join("Makefile");
  std::fs::write(&no_ext, "all:\n\techo hi\n").unwrap();
  let res_no_ext = diff_check_via_tempcopy(
    std::slice::from_ref(&no_ext),
    |scratch| {
      assert!(
        scratch
          .file_name()
          .unwrap()
          .to_str()
          .unwrap()
          .ends_with(".fml-check.tmp")
      );
      Ok(create_dummy_success_output())
    },
    "makefile",
    Instant::now(),
  );
  assert!(matches!(res_no_ext.status, SurfaceStatus::Passed));

  // Case B: Multi-dot file extension (e.g. app.test.spec.rs)
  let multi_ext = temp.path().join("app.test.spec.rs");
  std::fs::write(&multi_ext, "fn test() {}").unwrap();
  let res_multi = diff_check_via_tempcopy(
    std::slice::from_ref(&multi_ext),
    |scratch| {
      let name = scratch.file_name().unwrap().to_str().unwrap();
      assert!(name.contains("app.test.spec.fml-check-tmp.rs"));
      Ok(create_dummy_success_output())
    },
    "rust",
    Instant::now(),
  );
  assert!(matches!(res_multi.status, SurfaceStatus::Passed));

  // Case C: File in nested directory hierarchy
  let nested_dir = temp.path().join("nested").join("sub");
  std::fs::create_dir_all(&nested_dir).unwrap();
  let nested_file = nested_dir.join("script.py");
  std::fs::write(&nested_file, "print('hello')\n").unwrap();
  let res_nested = diff_check_via_tempcopy(
    std::slice::from_ref(&nested_file),
    |_scratch| Ok(create_dummy_success_output()),
    "python",
    Instant::now(),
  );
  assert!(matches!(res_nested.status, SurfaceStatus::Passed));

  // Case D: Filename with spaces and special characters
  let special_file = temp.path().join("my test #1 (draft).js");
  std::fs::write(&special_file, "console.log(1);").unwrap();
  let res_special = diff_check_via_tempcopy(
    std::slice::from_ref(&special_file),
    |_scratch| Ok(create_dummy_success_output()),
    "javascript",
    Instant::now(),
  );
  assert!(matches!(res_special.status, SurfaceStatus::Passed));
}

#[test]
fn test_diff_check_via_tempcopy_original_file_non_mutation_fuzzing() {
  let temp = TempDir::new().unwrap();
  let original_file = temp.path().join("fuzz_target.txt");
  let original_bytes = b"ORIGINAL_STABLE_CONTENT_DO_NOT_MUTATE_123456789";
  std::fs::write(&original_file, original_bytes).unwrap();

  // Test 1: Closure truncates scratch file
  let _ = diff_check_via_tempcopy(
    std::slice::from_ref(&original_file),
    |scratch| {
      std::fs::write(scratch, b"TRUNCATED").unwrap();
      Ok(create_dummy_success_output())
    },
    "text",
    Instant::now(),
  );
  assert_eq!(std::fs::read(&original_file).unwrap(), original_bytes);

  // Test 2: Closure completely deletes scratch file
  let _ = diff_check_via_tempcopy(
    std::slice::from_ref(&original_file),
    |scratch| {
      let _ = std::fs::remove_file(scratch);
      Ok(create_dummy_success_output())
    },
    "text",
    Instant::now(),
  );
  assert_eq!(std::fs::read(&original_file).unwrap(), original_bytes);

  // Test 3: Closure fills scratch with random binary garbage
  let _ = diff_check_via_tempcopy(
    std::slice::from_ref(&original_file),
    |scratch| {
      std::fs::write(scratch, [0x00, 0xFF, 0xFE, 0x12, 0x99]).unwrap();
      Ok(create_dummy_success_output())
    },
    "text",
    Instant::now(),
  );
  assert_eq!(std::fs::read(&original_file).unwrap(), original_bytes);
}

#[test]
fn test_diff_check_via_tempcopy_batch_processing_and_cleanup() {
  let temp = TempDir::new().unwrap();
  let files: Vec<_> = (0..5)
    .map(|i| {
      let p = temp.path().join(format!("batch_{i}.rs"));
      std::fs::write(&p, format!("fn f{i}() {{}}\n")).unwrap();
      p
    })
    .collect();

  // Multi-file run where element index 2 panics or returns error
  let start = Instant::now();
  let _ = diff_check_via_tempcopy(
    &files,
    |scratch| {
      if scratch.to_string_lossy().contains("batch_2") {
        return Err(std::io::Error::other("Simulated batch failure on file 2"));
      }
      Ok(create_dummy_success_output())
    },
    "rust",
    start,
  );

  // Ensure NO temp files left over for any of the batch files
  for f in &files {
    let scratch = f.with_file_name(format!(
      "{}.fml-check-tmp.rs",
      f.file_stem().unwrap().to_str().unwrap()
    ));
    assert!(
      !scratch.exists(),
      "Scratch file {:?} was not cleaned up!",
      scratch
    );
  }
}

#[test]
fn test_diff_check_via_tempcopy_content_variations() {
  let temp = TempDir::new().unwrap();

  // Empty file
  let empty = temp.path().join("empty.rs");
  std::fs::write(&empty, "").unwrap();
  let res_empty = diff_check_via_tempcopy(
    std::slice::from_ref(&empty),
    |_scratch| Ok(create_dummy_success_output()),
    "rust",
    Instant::now(),
  );
  assert!(matches!(res_empty.status, SurfaceStatus::Passed));

  // CRLF line endings
  let crlf = temp.path().join("crlf.rs");
  std::fs::write(&crlf, "line1\r\nline2\r\n").unwrap();
  let res_crlf = diff_check_via_tempcopy(
    std::slice::from_ref(&crlf),
    |scratch| {
      std::fs::write(scratch, "line1\nline2\n").unwrap();
      Ok(create_dummy_success_output())
    },
    "rust",
    Instant::now(),
  );
  assert!(matches!(
    res_crlf.status,
    SurfaceStatus::ViolationsFound { .. }
  ));
}
