//! `fml sync` support: auto-generation-header detection, the generic
//! expected-vs-current file sync helper, and the tempcopy-based diff-check
//! used by in-place formatters during `fml fmt --check`.

use super::{SurfaceResult, SurfaceStatus};
use crate::engine::diff::render_diff;
use std::path::{Path, PathBuf};
use std::time::Instant;

/// Returns true if `content` was written by `fml sync` (contains the
/// auto-generation sentinel comment). Used to guard against silently
/// overwriting hand-written configs.
#[must_use]
pub fn is_auto_generated(content: &str) -> bool {
  content.contains("DO NOT EDIT")
    || content.contains("Auto-generated by formality")
    || content.contains("WARNING: DO NOT EDIT THIS FILE DIRECTLY!")
}

#[must_use]
pub fn sync_file_helper(
  file_path: &Path,
  file_name: &str,
  expected_content: &str,
  check: bool,
  start: Instant,
  surface_name: &'static str,
) -> SurfaceResult {
  let exists = file_path.is_file();
  let current_content = if exists {
    std::fs::read_to_string(file_path).unwrap_or_default()
  } else {
    String::new()
  };

  if current_content.trim() == expected_content.trim() {
    return SurfaceResult {
      surface_name,
      status: SurfaceStatus::Passed,
      duration: start.elapsed(),
    };
  }

  // File exists but was not written by fml — protect it from silent overwrite.
  // The multi-clause condition explicitly distinguishes between presence, non-emptiness,
  // auto-generated header matching, and valid JSON config fallback.
  if exists
    && !current_content.is_empty()
    && !is_auto_generated(&current_content)
    && !(file_name == "biome.json"
      && serde_json::from_str::<super::javascript::BiomeConfig>(
        &current_content,
      )
      .is_ok())
  {
    let suggestion = format!(
      "'{file_name}' exists but was not generated by formality.\n\
       It will not be overwritten automatically to avoid destroying manual settings.\n\
       \n\
       To resolve, choose one of:\n\
       \n\
       Option A — Let formality manage the file:\n\
         1. Back up your current settings.\n\
         2. Delete '{file_name}' and run 'fml sync' to generate a clean copy.\n\
         3. Migrate any custom settings you need into formality.toml using\n\
            [lang.<name>] overrides (indent_size, line_length, extra_args, …).\n\
       \n\
       Option B — Keep managing the file yourself:\n\
         Add the following header as the very first block of '{file_name}'\n\
         to suppress this warning and opt out of sync for this file:\n\
         (You will need to run 'fml sync' again after adding the header,\n\
          formality will then leave that file untouched.)\n\
       \n\
       The header that formality looks for:\n\
         # WARNING: DO NOT EDIT THIS FILE DIRECTLY!\n\
         (or the JSON equivalent: a top-level \"$comment\" containing the same text)\n\
       \n\
       Generated config for reference:\n\
       ---\n\
       {expected_content}\n\
       ---"
    );
    return SurfaceResult {
      surface_name,
      status: SurfaceStatus::ManualConfig {
        file: file_name.to_string(),
        suggestion,
      },
      duration: start.elapsed(),
    };
  }

  if check {
    let diff = render_diff(
      &current_content,
      expected_content,
      if exists { file_name } else { "(missing)" },
      &format!("{file_name} (expected)"),
    );
    SurfaceResult {
      surface_name,
      status: SurfaceStatus::ConfigDrifted {
        file: file_name.to_string(),
        diff,
      },
      duration: start.elapsed(),
    }
  } else {
    if let Some(parent) = file_path.parent() {
      let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::write(file_path, expected_content) {
      Ok(()) => SurfaceResult {
        surface_name,
        status: SurfaceStatus::ConfigSynced {
          file: file_name.to_string(),
          created: !exists,
        },
        duration: start.elapsed(),
      },
      Err(e) => SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to write {file_name}: {e}"),
        },
        duration: start.elapsed(),
      },
    }
  }
}

struct TempFileGuard<'a>(&'a Path);

impl Drop for TempFileGuard<'_> {
  fn drop(&mut self) {
    let _ = std::fs::remove_file(self.0);
  }
}

/// Executes an in-place formatter on temporary copies of the given files and generates
/// unified diffs between the original content and the formatted content.
///
/// Uses an RAII guard to guarantee that `.fml-check.tmp` files are cleaned up on all exit paths.
// Implements temporary-file copy, in-place formatting execution, unified diff generation, and RAII cleanup across file sets.
#[allow(clippy::too_many_lines)]
pub fn diff_check_via_tempcopy(
  files: &[PathBuf],
  run_in_place: impl Fn(&Path) -> std::io::Result<std::process::Output>,
  surface_name: &'static str,
  start: Instant,
) -> SurfaceResult {
  if files.is_empty() {
    return SurfaceResult {
      surface_name,
      status: SurfaceStatus::Passed,
      duration: start.elapsed(),
    };
  }

  let mut combined_diff = String::new();

  for original in files {
    let original_content = match std::fs::read_to_string(original) {
      Ok(c) => c,
      Err(e) => {
        return SurfaceResult {
          surface_name,
          status: SurfaceStatus::ExecutionError {
            message: format!("Failed to read {}: {}", original.display(), e),
          },
          duration: start.elapsed(),
        };
      }
    };

    let ext = original.extension().and_then(|e| e.to_str()).unwrap_or("");
    let scratch = if ext.is_empty() {
      original.with_extension("fml-check.tmp")
    } else {
      let file_stem =
        original.file_stem().and_then(|s| s.to_str()).unwrap_or("");
      original.with_file_name(format!("{file_stem}.fml-check-tmp.{ext}"))
    };

    if let Err(e) = std::fs::write(&scratch, &original_content) {
      return SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!(
            "Failed to write temp file {}: {}",
            scratch.display(),
            e
          ),
        },
        duration: start.elapsed(),
      };
    }

    let _guard = TempFileGuard(&scratch);

    let output = match run_in_place(&scratch) {
      Ok(out) => out,
      Err(e) => {
        return SurfaceResult {
          surface_name,
          status: SurfaceStatus::ExecutionError {
            message: format!(
              "Failed to run formatter for {}: {}",
              original.display(),
              e
            ),
          },
          duration: start.elapsed(),
        };
      }
    };

    if !output.status.success() {
      let stderr = String::from_utf8_lossy(&output.stderr).to_string();
      let stdout = String::from_utf8_lossy(&output.stdout).to_string();
      let msg = if !stderr.trim().is_empty() {
        stderr
      } else if !stdout.trim().is_empty() {
        stdout
      } else {
        format!("Formatter failed for {}", original.display())
      };
      return SurfaceResult {
        surface_name,
        status: SurfaceStatus::ViolationsFound {
          message: msg,
          diff: None,
        },
        duration: start.elapsed(),
      };
    }

    let formatted = match std::fs::read_to_string(&scratch) {
      Ok(f) => f,
      Err(e) => {
        return SurfaceResult {
          surface_name,
          status: SurfaceStatus::ExecutionError {
            message: format!(
              "Failed to read formatted temp file {}: {}",
              scratch.display(),
              e
            ),
          },
          duration: start.elapsed(),
        };
      }
    };

    if formatted != original_content {
      let diff = render_diff(
        &original_content,
        &formatted,
        &original.display().to_string(),
        &format!("{} (formatted)", original.display()),
      );
      if !combined_diff.is_empty() {
        combined_diff.push('\n');
      }
      combined_diff.push_str(&diff);
    }
  }

  if combined_diff.is_empty() {
    SurfaceResult {
      surface_name,
      status: SurfaceStatus::Passed,
      duration: start.elapsed(),
    }
  } else {
    SurfaceResult {
      surface_name,
      status: SurfaceStatus::ViolationsFound {
        message: String::new(),
        diff: Some(combined_diff),
      },
      duration: start.elapsed(),
    }
  }
}

#[cfg(test)]
#[path = "sync_tests.rs"]
mod tests;
