//! `fml sync` support: auto-generation-header detection, the generic
//! expected-vs-current file sync helper, and the tempcopy-based diff-check
//! used by in-place formatters during `fml fmt --check`.

use super::tooling::merge_tool_streams;
use super::{ExitClass, SurfaceResult, SurfaceStatus, SyncedConfigFile};
use crate::engine::diff::render_diff;
use rayon::prelude::*;
use std::path::{Path, PathBuf};
use std::time::Instant;

/// Returns true if `content` was written by `fml sync` (contains the
/// auto-generation sentinel comment). Used to guard against silently
/// overwriting hand-written configs.
#[must_use]
pub fn is_auto_generated(content: &str) -> bool {
  content.contains("DO NOT EDIT")
    || content.contains("Auto-generated by formality")
    || content.contains("WARNING: DO NOT EDIT THIS FILE DIRECTLY!")
}

/// Writes `expected_content` to `file_path` (or, with `check`, only reports
/// whether it would differ) unless the existing file was hand-edited (not
/// [`is_auto_generated`]), in which case the write is skipped to avoid
/// clobbering it.
#[must_use]
pub fn sync_file_helper(
  file_path: &Path,
  file_name: &str,
  expected_content: &str,
  check: bool,
  start: Instant,
  surface_name: &'static str,
) -> SurfaceResult {
  let exists = file_path.is_file();
  let current_content = if exists {
    std::fs::read_to_string(file_path).unwrap_or_default()
  } else {
    String::new()
  };

  if current_content.trim() == expected_content.trim() {
    return SurfaceResult {
      surface_name,
      status: SurfaceStatus::Passed,
      duration: start.elapsed(),
    };
  }

  // File exists but was not written by fml — protect it from silent overwrite.
  if exists
    && !current_content.is_empty()
    && !is_auto_generated(&current_content)
  {
    let suggestion = format!(
      "'{file_name}' exists but was not generated by formality.\n\
       It will not be overwritten automatically to avoid destroying manual settings.\n\
       \n\
       To resolve, choose one of:\n\
       \n\
       Option A — Let formality manage the file:\n\
         1. Back up your current settings.\n\
         2. Delete '{file_name}' and run 'fml sync' to generate a clean copy.\n\
         3. Migrate any custom settings you need into formality.toml using\n\
            [lang.<name>] overrides (indent_size, line_length, extra_args, …).\n\
       \n\
       Option B — Keep managing the file yourself:\n\
         Add the following header as the very first block of '{file_name}'\n\
         to suppress this warning and opt out of sync for this file:\n\
         (You will need to run 'fml sync' again after adding the header,\n\
          formality will then leave that file untouched.)\n\
       \n\
       The header that formality looks for:\n\
         # WARNING: DO NOT EDIT THIS FILE DIRECTLY!\n\
         (or the JSON equivalent: a top-level \"$comment\" containing the same text)\n\
       \n\
       Generated config for reference:\n\
       ---\n\
       {expected_content}\n\
       ---"
    );
    return SurfaceResult {
      surface_name,
      status: SurfaceStatus::ManualConfig {
        file: file_name.to_string(),
        suggestion,
      },
      duration: start.elapsed(),
    };
  }

  if check {
    let diff = render_diff(
      &current_content,
      expected_content,
      if exists { file_name } else { "(missing)" },
      &format!("{file_name} (expected)"),
    );
    SurfaceResult {
      surface_name,
      status: SurfaceStatus::ConfigDrifted {
        file: file_name.to_string(),
        diff,
      },
      duration: start.elapsed(),
    }
  } else {
    if let Some(parent) = file_path.parent() {
      let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::write(file_path, expected_content) {
      Ok(()) => SurfaceResult {
        surface_name,
        status: SurfaceStatus::ConfigSynced {
          files: vec![SyncedConfigFile::new(file_name, !exists)],
        },
        duration: start.elapsed(),
      },
      Err(e) => SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to write {file_name}: {e}"),
        },
        duration: start.elapsed(),
      },
    }
  }
}

/// Folds the per-file results of a surface that syncs more than one native
/// config file into the single [`SurfaceResult`] the runner renders for it.
///
/// Before #130 such a surface simply returned its *last* successful result
/// and dropped the rest, so `fml sync` could write `.markdownlint.json` and
/// then report only what prettier did — a file created on disk and named
/// nowhere in the output. Merging keeps every filename.
///
/// Semantics:
///
/// - The first non-success (drift, manual config, execution error) is
///   returned as-is. It already names the file it is about, and a surface
///   stops at its first failure rather than writing the remaining files, so
///   there is nothing further to report.
/// - Otherwise every [`SurfaceStatus::ConfigSynced`] file list is
///   concatenated in call order. If nothing was written — every file was
///   already correct — the merged status is [`SurfaceStatus::Passed`].
/// - Durations sum, so the reported time covers all the work done. Callers
///   must therefore time each file from its own [`Instant`] rather than
///   sharing one start.
///
/// # Panics
///
/// Panics on an empty slice in debug builds; a surface that syncs no file at
/// all reports [`SurfaceStatus::Skipped`] directly and never calls this.
#[must_use]
pub fn merge_sync_results(results: Vec<SurfaceResult>) -> SurfaceResult {
  debug_assert!(
    !results.is_empty(),
    "merge_sync_results called with no results"
  );
  let surface_name = results.first().map_or("", |r| r.surface_name);
  let duration = results.iter().map(|r| r.duration).sum();

  if let Some(failed) = results.iter().find(|r| !r.is_success()) {
    return SurfaceResult {
      surface_name,
      status: failed.status.clone(),
      duration,
    };
  }

  let files: Vec<SyncedConfigFile> = results
    .iter()
    .flat_map(|r| r.status.synced_files().iter().cloned())
    .collect();

  let status = if files.is_empty() {
    SurfaceStatus::Passed
  } else {
    SurfaceStatus::ConfigSynced { files }
  };

  SurfaceResult {
    surface_name,
    status,
    duration,
  }
}

enum PerFileCheckResult {
  Clean,
  Diff(String),
  /// The formatter exited non-zero. `message` already merges both captured
  /// streams; `code` is [`std::process::ExitStatus::code`] for the caller's
  /// classifier.
  FormatterError {
    message: String,
    code: Option<i32>,
  },
  ExecutionError(String),
}

/// Executes an in-place formatter on temporary copies of the given files in
/// parallel and generates unified diffs between the original content and the
/// formatted content, treating **any** non-zero formatter exit as
/// [`SurfaceStatus::ViolationsFound`].
///
/// Surfaces whose formatter distinguishes "could not run" from a formatting
/// result via its exit code should call [`diff_check_via_tempcopy_classified`]
/// so a tool *failure* is reported as [`SurfaceStatus::ExecutionError`],
/// consistently with the non-`--check` write path.
pub fn diff_check_via_tempcopy(
  files: &[PathBuf],
  run_in_place: impl Fn(&Path) -> std::io::Result<std::process::Output> + Sync,
  surface_name: &'static str,
  start: Instant,
) -> SurfaceResult {
  diff_check_via_tempcopy_classified(
    files,
    run_in_place,
    surface_name,
    start,
    |_| ExitClass::ViolationsFound,
  )
}

/// Like [`diff_check_via_tempcopy`], but lets the caller classify a non-zero
/// formatter exit code as either a formatting result or a tool failure via
/// `classify` (receives [`std::process::ExitStatus::code`], `None` on a
/// signal). On a non-zero exit both captured streams are surfaced when both
/// are non-empty — no non-empty stream is discarded.
///
/// Uses an isolated temporary directory under [`std::env::temp_dir()`] so that
/// scratch files do not pollute the workspace, and guarantees cleanup on all
/// exit paths.
// Implements temporary-file copy, in-place formatting execution, unified diff generation, and RAII cleanup across file sets.
#[allow(clippy::too_many_lines)]
pub fn diff_check_via_tempcopy_classified(
  files: &[PathBuf],
  run_in_place: impl Fn(&Path) -> std::io::Result<std::process::Output> + Sync,
  surface_name: &'static str,
  start: Instant,
  classify: impl Fn(Option<i32>) -> ExitClass,
) -> SurfaceResult {
  if files.is_empty() {
    return SurfaceResult {
      surface_name,
      status: SurfaceStatus::Passed,
      duration: start.elapsed(),
    };
  }

  let temp_dir = match tempfile::Builder::new()
    .prefix("fml-check-")
    .tempdir_in(std::env::temp_dir())
  {
    Ok(dir) => dir,
    Err(e) => {
      return SurfaceResult {
        surface_name,
        status: SurfaceStatus::ExecutionError {
          message: format!("Failed to create temporary directory: {e}"),
        },
        duration: start.elapsed(),
      };
    }
  };

  let temp_path = temp_dir.path();
  let results: Vec<PerFileCheckResult> = files
    .par_iter()
    .enumerate()
    .map(|(idx, original)| {
      let original_content = match std::fs::read_to_string(original) {
        Ok(c) => c,
        Err(e) => {
          return PerFileCheckResult::ExecutionError(format!(
            "Failed to read {}: {}",
            original.display(),
            e
          ));
        }
      };

      let file_name = original
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("scratch");
      let file_subfolder = temp_path.join(idx.to_string());
      if let Err(e) = std::fs::create_dir_all(&file_subfolder) {
        return PerFileCheckResult::ExecutionError(format!(
          "Failed to create temp directory {}: {}",
          file_subfolder.display(),
          e
        ));
      }
      let scratch = file_subfolder.join(file_name);

      if let Err(e) = std::fs::write(&scratch, &original_content) {
        return PerFileCheckResult::ExecutionError(format!(
          "Failed to write temp file {}: {}",
          scratch.display(),
          e
        ));
      }

      let output = match run_in_place(&scratch) {
        Ok(out) => out,
        Err(e) => {
          return PerFileCheckResult::ExecutionError(format!(
            "Failed to run formatter for {}: {}",
            original.display(),
            e
          ));
        }
      };

      if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        let message = merge_tool_streams(
          &stdout,
          &stderr,
          &format!("Formatter failed for {}", original.display()),
        );
        return PerFileCheckResult::FormatterError {
          message,
          code: output.status.code(),
        };
      }

      let formatted = match std::fs::read_to_string(&scratch) {
        Ok(f) => f,
        Err(e) => {
          return PerFileCheckResult::ExecutionError(format!(
            "Failed to read formatted temp file {}: {}",
            scratch.display(),
            e
          ));
        }
      };

      if formatted != original_content {
        let diff = render_diff(
          &original_content,
          &formatted,
          &original.display().to_string(),
          &format!("{} (formatted)", original.display()),
        );
        PerFileCheckResult::Diff(diff)
      } else {
        PerFileCheckResult::Clean
      }
    })
    .collect();

  let mut combined_diff = String::new();

  for result in results {
    match result {
      PerFileCheckResult::ExecutionError(message) => {
        return SurfaceResult {
          surface_name,
          status: SurfaceStatus::ExecutionError { message },
          duration: start.elapsed(),
        };
      }
      PerFileCheckResult::FormatterError { message, code } => {
        let status = match classify(code) {
          ExitClass::ViolationsFound => SurfaceStatus::ViolationsFound {
            message,
            diff: None,
          },
          ExitClass::ExecutionError => {
            SurfaceStatus::ExecutionError { message }
          }
        };
        return SurfaceResult {
          surface_name,
          status,
          duration: start.elapsed(),
        };
      }
      PerFileCheckResult::Diff(diff) => {
        if !combined_diff.is_empty() {
          combined_diff.push('\n');
        }
        combined_diff.push_str(&diff);
      }
      PerFileCheckResult::Clean => {}
    }
  }

  if combined_diff.is_empty() {
    SurfaceResult {
      surface_name,
      status: SurfaceStatus::Passed,
      duration: start.elapsed(),
    }
  } else {
    SurfaceResult {
      surface_name,
      status: SurfaceStatus::ViolationsFound {
        message: String::new(),
        diff: Some(combined_diff),
      },
      duration: start.elapsed(),
    }
  }
}

#[cfg(test)]
#[allow(missing_docs, clippy::missing_errors_doc, clippy::missing_panics_doc)]
mod tests {
  use super::*;
  use crate::surfaces::SurfaceStatus;
  use tempfile::TempDir;

  fn create_dummy_success_output() -> std::process::Output {
    #[cfg(windows)]
    {
      std::process::Command::new("cmd")
        .args(["/C", "exit 0"])
        .output()
        .expect("cmd exit 0 failed")
    }
    #[cfg(not(windows))]
    {
      std::process::Command::new("true")
        .output()
        .expect("true failed")
    }
  }

  /// A real `Output` that writes `stdout`/`stderr` (each skipped when empty)
  /// and exits with `code`, via the platform shell — so tests exercise the
  /// same `ExitStatus`/stream plumbing production does.
  fn scripted_output(
    stdout: &str,
    stderr: &str,
    code: i32,
  ) -> std::process::Output {
    #[cfg(windows)]
    {
      let mut steps: Vec<String> = Vec::new();
      if !stdout.is_empty() {
        steps.push(format!("echo {stdout}"));
      }
      if !stderr.is_empty() {
        steps.push(format!("echo {stderr} 1>&2"));
      }
      steps.push(format!("exit /b {code}"));
      std::process::Command::new("cmd")
        .arg("/C")
        .arg(steps.join(" & "))
        .output()
        .expect("scripted cmd failed")
    }
    #[cfg(not(windows))]
    {
      let mut script = String::new();
      if !stdout.is_empty() {
        script.push_str(&format!("printf '%s\\n' '{stdout}'; "));
      }
      if !stderr.is_empty() {
        script.push_str(&format!("printf '%s\\n' '{stderr}' 1>&2; "));
      }
      script.push_str(&format!("exit {code}"));
      std::process::Command::new("sh")
        .arg("-c")
        .arg(script)
        .output()
        .expect("scripted sh failed")
    }
  }

  #[test]
  fn test_is_auto_generated_recognizes_all_header_variants() {
    // is_auto_generated is the guard that decides whether fml is allowed to
    // silently overwrite an existing config file. It had zero test coverage
    // despite gating the ManualConfig-vs-ConfigSynced branch entirely.
    assert!(is_auto_generated("# DO NOT EDIT this generated file\n..."));
    assert!(is_auto_generated("// Auto-generated by formality\nfoo = 1"));
    assert!(is_auto_generated(
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nfoo = 1"
    ));
    assert!(!is_auto_generated("foo = 1\nbar = 2\n"));
    assert!(!is_auto_generated(""));
  }

  #[test]
  fn test_sync_file_helper_creates_missing_file() {
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(".rustfmt.toml");
    let start = Instant::now();

    let res = sync_file_helper(
      &path,
      ".rustfmt.toml",
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
      false,
      start,
      "rust",
    );

    assert_eq!(res.status.created_file_names(), [".rustfmt.toml"]);
    assert!(path.is_file());
    assert_eq!(
      std::fs::read_to_string(&path).unwrap(),
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n"
    );
  }

  #[test]
  fn test_sync_file_helper_matching_content_is_passed() {
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(".rustfmt.toml");
    // Trailing whitespace differences must not count as drift (comparison is
    // trim()'d on both sides).
    std::fs::write(&path, "max_width = 80\n\n  ").unwrap();

    let res = sync_file_helper(
      &path,
      ".rustfmt.toml",
      "max_width = 80",
      false,
      Instant::now(),
      "rust",
    );
    assert!(matches!(res.status, SurfaceStatus::Passed));
  }

  #[test]
  fn test_sync_file_helper_auto_generated_drift_is_overwritten() {
    // A file previously written by fml (carries the header) that has since
    // drifted from the expected content must be silently rewritten in
    // non-check mode — the manual-config protection must NOT trigger here.
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(".rustfmt.toml");
    std::fs::write(
      &path,
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 100\n",
    )
    .unwrap();

    let res = sync_file_helper(
      &path,
      ".rustfmt.toml",
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
      false,
      Instant::now(),
      "rust",
    );

    assert_eq!(res.status.synced_file_names(), [".rustfmt.toml"]);
    assert!(res.status.created_file_names().is_empty());
    assert!(
      std::fs::read_to_string(&path)
        .unwrap()
        .contains("max_width = 80")
    );
  }

  #[test]
  fn test_sync_file_helper_auto_generated_drift_check_mode_reports_diff() {
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(".rustfmt.toml");
    std::fs::write(
      &path,
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 100\n",
    )
    .unwrap();

    let res = sync_file_helper(
      &path,
      ".rustfmt.toml",
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
      true,
      Instant::now(),
      "rust",
    );

    match res.status {
      SurfaceStatus::ConfigDrifted { file, diff } => {
        assert_eq!(file, ".rustfmt.toml");
        assert!(diff.contains("max_width"));
      }
      other => panic!("expected ConfigDrifted, got {other:?}"),
    }
    // check mode must never write to disk.
    assert!(
      std::fs::read_to_string(&path)
        .unwrap()
        .contains("max_width = 100")
    );
  }

  #[test]
  fn test_sync_file_helper_manual_file_is_protected_from_overwrite() {
    // A hand-written config with no fml header must never be silently
    // clobbered, in either check or write mode — this is the exact
    // protection this project's own pre-commit hook (.githooks/pre-commit,
    // `fml sync --check`) relies on to avoid destroying user settings.
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(".rustfmt.toml");
    std::fs::write(&path, "max_width = 120\n# hand-tuned, no header\n")
      .unwrap();

    let res_write = sync_file_helper(
      &path,
      ".rustfmt.toml",
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
      false,
      Instant::now(),
      "rust",
    );
    match res_write.status {
      SurfaceStatus::ManualConfig { file, suggestion } => {
        assert_eq!(file, ".rustfmt.toml");
        assert!(suggestion.contains("was not generated by formality"));
        assert!(suggestion.contains("max_width = 80"));
      }
      other => panic!("expected ManualConfig, got {other:?}"),
    }
    // The file on disk must be untouched.
    assert_eq!(
      std::fs::read_to_string(&path).unwrap(),
      "max_width = 120\n# hand-tuned, no header\n"
    );

    let res_check = sync_file_helper(
      &path,
      ".rustfmt.toml",
      "# WARNING: DO NOT EDIT THIS FILE DIRECTLY!\nmax_width = 80\n",
      true,
      Instant::now(),
      "rust",
    );
    assert!(matches!(
      res_check.status,
      SurfaceStatus::ManualConfig { .. }
    ));
  }

  #[test]
  fn test_sync_file_helper_json_without_header_is_protected_as_manual() {
    // Hand-written JSON configs (e.g. .prettierrc.json, biome.json) with no fml header
    // or $comment must be protected from silent overwrite.
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(".prettierrc.json");
    std::fs::write(
      &path,
      r#"{"tabWidth":2,"printWidth":80,"useTabs":false,"endOfLine":"lf","proseWrap":"preserve"}"#,
    )
    .unwrap();

    let expected = r#"{
  "$comment": "WARNING: DO NOT EDIT THIS FILE DIRECTLY!",
  "tabWidth": 4,
  "printWidth": 100,
  "useTabs": false,
  "endOfLine": "lf",
  "proseWrap": "preserve"
}"#;

    let res = sync_file_helper(
      &path,
      ".prettierrc.json",
      expected,
      false,
      Instant::now(),
      "markdown",
    );
    assert!(matches!(
      res.status,
      SurfaceStatus::ManualConfig { file, .. } if file == ".prettierrc.json"
    ));

    let biome_path = temp.path().join("biome.json");
    std::fs::write(&biome_path, r#"{"formatter": {"enabled": true}}"#).unwrap();

    let res_biome = sync_file_helper(
      &biome_path,
      "biome.json",
      expected,
      false,
      Instant::now(),
      "javascript",
    );
    assert!(matches!(
      res_biome.status,
      SurfaceStatus::ManualConfig { file, .. } if file == "biome.json"
    ));
  }

  #[test]
  fn test_diff_check_via_tempcopy_clean() {
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("clean.rs");
    std::fs::write(&file, "fn main() {\n  println!(\"clean\");\n}\n").unwrap();

    let scratch_path = std::sync::Mutex::new(PathBuf::new());
    let start = Instant::now();
    let res = diff_check_via_tempcopy(
      std::slice::from_ref(&file),
      |scratch| {
        *scratch_path.lock().unwrap() = scratch.to_path_buf();
        assert_ne!(scratch.parent().unwrap(), temp.path());
        assert!(scratch.exists());
        Ok(create_dummy_success_output())
      },
      "rust",
      start,
    );

    assert!(matches!(res.status, SurfaceStatus::Passed));
    assert!(!scratch_path.lock().unwrap().exists());
    assert_eq!(std::fs::read_dir(temp.path()).unwrap().count(), 1);
  }

  #[test]
  fn test_diff_check_via_tempcopy_with_diff() {
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("dirty.rs");
    std::fs::write(&file, "fn main() {let x=1;}").unwrap();

    let scratch_path = std::sync::Mutex::new(PathBuf::new());
    let start = Instant::now();
    let res = diff_check_via_tempcopy(
      std::slice::from_ref(&file),
      |scratch| {
        *scratch_path.lock().unwrap() = scratch.to_path_buf();
        std::fs::write(scratch, "fn main() {\n  let x = 1;\n}\n")?;
        Ok(create_dummy_success_output())
      },
      "rust",
      start,
    );

    match res.status {
      SurfaceStatus::ViolationsFound { message, diff } => {
        assert!(message.is_empty());
        let diff_str = diff.expect("diff should be present");
        assert!(diff_str.contains("dirty.rs"));
        assert!(diff_str.contains("(formatted)"));
      }
      other => panic!("Expected ViolationsFound, got {other:?}"),
    }

    assert!(!scratch_path.lock().unwrap().exists());
    assert_eq!(std::fs::read_dir(temp.path()).unwrap().count(), 1);
  }

  #[test]
  fn test_diff_check_via_tempcopy_raii_cleanup_on_error() {
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("error_case.rs");
    std::fs::write(&file, "invalid syntax").unwrap();

    let scratch_path = std::sync::Mutex::new(PathBuf::new());
    let start = Instant::now();
    let res = diff_check_via_tempcopy(
      std::slice::from_ref(&file),
      |scratch| {
        *scratch_path.lock().unwrap() = scratch.to_path_buf();
        Err(std::io::Error::other("mock execution error"))
      },
      "rust",
      start,
    );

    assert!(matches!(res.status, SurfaceStatus::ExecutionError { .. }));
    assert!(!scratch_path.lock().unwrap().exists());
    assert_eq!(std::fs::read_dir(temp.path()).unwrap().count(), 1);
  }

  #[test]
  fn test_diff_check_via_tempcopy_raii_cleanup_on_panic() {
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("panic_case.rs");
    std::fs::write(&file, "panic content").unwrap();

    let scratch_path = std::sync::Mutex::new(PathBuf::new());
    let start = Instant::now();
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
      diff_check_via_tempcopy(
        std::slice::from_ref(&file),
        |scratch| {
          *scratch_path.lock().unwrap() = scratch.to_path_buf();
          panic!("simulated panic inside run_in_place");
        },
        "rust",
        start,
      );
    }));

    assert!(!scratch_path.lock().unwrap().exists());
    assert_eq!(std::fs::read_dir(temp.path()).unwrap().count(), 1);
  }

  #[test]
  fn test_diff_check_via_tempcopy_naming_and_path_edge_cases() {
    let temp = TempDir::new().unwrap();

    // Case A: File with no extension (e.g., Makefile)
    let no_ext = temp.path().join("Makefile");
    std::fs::write(&no_ext, "all:\n\techo hi\n").unwrap();
    let res_no_ext = diff_check_via_tempcopy(
      std::slice::from_ref(&no_ext),
      |scratch| {
        assert_eq!(scratch.file_name().unwrap().to_str().unwrap(), "Makefile");
        assert_ne!(scratch.parent().unwrap(), temp.path());
        Ok(create_dummy_success_output())
      },
      "makefile",
      Instant::now(),
    );
    assert!(matches!(res_no_ext.status, SurfaceStatus::Passed));

    // Case B: Multi-dot file extension (e.g. app.test.spec.rs)
    let multi_ext = temp.path().join("app.test.spec.rs");
    std::fs::write(&multi_ext, "fn test() {}").unwrap();
    let res_multi = diff_check_via_tempcopy(
      std::slice::from_ref(&multi_ext),
      |scratch| {
        let name = scratch.file_name().unwrap().to_str().unwrap();
        assert_eq!(name, "app.test.spec.rs");
        assert_ne!(scratch.parent().unwrap(), temp.path());
        Ok(create_dummy_success_output())
      },
      "rust",
      Instant::now(),
    );
    assert!(matches!(res_multi.status, SurfaceStatus::Passed));

    // Case C: File in nested directory hierarchy
    let nested_dir = temp.path().join("nested").join("sub");
    std::fs::create_dir_all(&nested_dir).unwrap();
    let nested_file = nested_dir.join("script.py");
    std::fs::write(&nested_file, "print('hello')\n").unwrap();
    let res_nested = diff_check_via_tempcopy(
      std::slice::from_ref(&nested_file),
      |scratch| {
        assert_eq!(scratch.file_name().unwrap().to_str().unwrap(), "script.py");
        assert_ne!(scratch.parent().unwrap(), nested_dir);
        Ok(create_dummy_success_output())
      },
      "python",
      Instant::now(),
    );
    assert!(matches!(res_nested.status, SurfaceStatus::Passed));

    // Case D: Filename with spaces and special characters
    let special_file = temp.path().join("my test #1 (draft).js");
    std::fs::write(&special_file, "console.log(1);").unwrap();
    let res_special = diff_check_via_tempcopy(
      std::slice::from_ref(&special_file),
      |scratch| {
        assert_eq!(
          scratch.file_name().unwrap().to_str().unwrap(),
          "my test #1 (draft).js"
        );
        assert_ne!(scratch.parent().unwrap(), temp.path());
        Ok(create_dummy_success_output())
      },
      "javascript",
      Instant::now(),
    );
    assert!(matches!(res_special.status, SurfaceStatus::Passed));
  }

  #[test]
  fn test_diff_check_via_tempcopy_original_file_non_mutation_fuzzing() {
    let temp = TempDir::new().unwrap();
    let original_file = temp.path().join("fuzz_target.txt");
    let original_bytes = b"ORIGINAL_STABLE_CONTENT_DO_NOT_MUTATE_123456789";
    std::fs::write(&original_file, original_bytes).unwrap();

    // Test 1: Closure truncates scratch file
    let _ = diff_check_via_tempcopy(
      std::slice::from_ref(&original_file),
      |scratch| {
        std::fs::write(scratch, b"TRUNCATED").unwrap();
        Ok(create_dummy_success_output())
      },
      "text",
      Instant::now(),
    );
    assert_eq!(std::fs::read(&original_file).unwrap(), original_bytes);

    // Test 2: Closure completely deletes scratch file
    let _ = diff_check_via_tempcopy(
      std::slice::from_ref(&original_file),
      |scratch| {
        let _ = std::fs::remove_file(scratch);
        Ok(create_dummy_success_output())
      },
      "text",
      Instant::now(),
    );
    assert_eq!(std::fs::read(&original_file).unwrap(), original_bytes);

    // Test 3: Closure fills scratch with random binary garbage
    let _ = diff_check_via_tempcopy(
      std::slice::from_ref(&original_file),
      |scratch| {
        std::fs::write(scratch, [0x00, 0xFF, 0xFE, 0x12, 0x99]).unwrap();
        Ok(create_dummy_success_output())
      },
      "text",
      Instant::now(),
    );
    assert_eq!(std::fs::read(&original_file).unwrap(), original_bytes);
  }

  #[test]
  fn test_diff_check_via_tempcopy_batch_processing_and_cleanup() {
    let temp = TempDir::new().unwrap();
    let files: Vec<_> = (0..5)
      .map(|i| {
        let p = temp.path().join(format!("batch_{i}.rs"));
        std::fs::write(&p, format!("fn f{i}() {{}}\n")).unwrap();
        p
      })
      .collect();

    // Multi-file run where element index 2 panics or returns error
    let start = Instant::now();
    let _ = diff_check_via_tempcopy(
      &files,
      |scratch| {
        if scratch.to_string_lossy().contains("batch_2") {
          return Err(std::io::Error::other(
            "Simulated batch failure on file 2",
          ));
        }
        Ok(create_dummy_success_output())
      },
      "rust",
      start,
    );

    // Ensure NO temp files left over in workspace
    assert_eq!(
      std::fs::read_dir(temp.path()).unwrap().count(),
      5,
      "Only the 5 original batch files should exist in workspace"
    );
  }

  #[test]
  fn test_diff_check_via_tempcopy_content_variations() {
    let temp = TempDir::new().unwrap();

    // Empty file
    let empty = temp.path().join("empty.rs");
    std::fs::write(&empty, "").unwrap();
    let res_empty = diff_check_via_tempcopy(
      std::slice::from_ref(&empty),
      |_scratch| Ok(create_dummy_success_output()),
      "rust",
      Instant::now(),
    );
    assert!(matches!(res_empty.status, SurfaceStatus::Passed));

    // CRLF line endings
    let crlf = temp.path().join("crlf.rs");
    std::fs::write(&crlf, "line1\r\nline2\r\n").unwrap();
    let res_crlf = diff_check_via_tempcopy(
      std::slice::from_ref(&crlf),
      |scratch| {
        std::fs::write(scratch, "line1\nline2\n").unwrap();
        Ok(create_dummy_success_output())
      },
      "rust",
      Instant::now(),
    );
    assert!(matches!(
      res_crlf.status,
      SurfaceStatus::ViolationsFound { .. }
    ));
  }

  #[test]
  fn test_diff_check_via_tempcopy_parallel_multi_file_diff_ordering() {
    let temp = TempDir::new().unwrap();
    let files: Vec<_> = (0..8)
      .map(|i| {
        let p = temp.path().join(format!("order_test_{i}.rs"));
        std::fs::write(&p, format!("fn file_{i}() {{}}\n")).unwrap();
        p
      })
      .collect();

    let start = Instant::now();
    let res = diff_check_via_tempcopy(
      &files,
      |scratch| {
        let name = scratch.file_name().unwrap().to_str().unwrap();
        // Modify even indexed files only
        if let Some(num_str) = name
          .strip_prefix("order_test_")
          .and_then(|s| s.strip_suffix(".rs"))
        {
          let num: usize = num_str.parse().unwrap();
          if num.is_multiple_of(2) {
            std::fs::write(
              scratch,
              format!("fn file_{num}() {{ /* formatted */ }}\n"),
            )?;
          }
        }
        Ok(create_dummy_success_output())
      },
      "rust",
      start,
    );

    match res.status {
      SurfaceStatus::ViolationsFound { message, diff } => {
        assert!(message.is_empty());
        let diff_str = diff.expect("diff should be present");
        let pos0 = diff_str
          .find("order_test_0.rs")
          .expect("order_test_0 present");
        let pos2 = diff_str
          .find("order_test_2.rs")
          .expect("order_test_2 present");
        let pos4 = diff_str
          .find("order_test_4.rs")
          .expect("order_test_4 present");
        let pos6 = diff_str
          .find("order_test_6.rs")
          .expect("order_test_6 present");
        assert!(pos0 < pos2, "diff for file 0 must precede file 2");
        assert!(pos2 < pos4, "diff for file 2 must precede file 4");
        assert!(pos4 < pos6, "diff for file 4 must precede file 6");
        assert!(!diff_str.contains("order_test_1.rs"));
        assert!(!diff_str.contains("order_test_3.rs"));
      }
      other => panic!("Expected ViolationsFound, got {other:?}"),
    }
  }

  #[test]
  fn test_diff_check_via_tempcopy_parallel_deterministic_error_priority() {
    let temp = TempDir::new().unwrap();
    let files: Vec<_> = (0..6)
      .map(|i| {
        let p = temp.path().join(format!("err_prio_{i}.rs"));
        std::fs::write(&p, format!("fn err_{i}() {{}}\n")).unwrap();
        p
      })
      .collect();

    let start = Instant::now();
    let res = diff_check_via_tempcopy(
      &files,
      |scratch| {
        let name = scratch.file_name().unwrap().to_str().unwrap();
        if name.contains("err_prio_2") {
          return Err(std::io::Error::other("Failure at index 2"));
        }
        if name.contains("err_prio_4") {
          return Err(std::io::Error::other("Failure at index 4"));
        }
        Ok(create_dummy_success_output())
      },
      "rust",
      start,
    );

    match res.status {
      SurfaceStatus::ExecutionError { message } => {
        assert!(
          message.contains("err_prio_2"),
          "Expected earliest failing file (index 2) to be reported, got: {message}"
        );
      }
      other => panic!("Expected ExecutionError, got {other:?}"),
    }
  }

  #[test]
  fn test_diff_check_via_tempcopy_parallel_all_clean_multiple_files() {
    let temp = TempDir::new().unwrap();
    let files: Vec<_> = (0..10)
      .map(|i| {
        let p = temp.path().join(format!("clean_{i}.rs"));
        std::fs::write(&p, format!("fn clean_{i}() {{}}\n")).unwrap();
        p
      })
      .collect();

    let res = diff_check_via_tempcopy(
      &files,
      |_scratch| Ok(create_dummy_success_output()),
      "rust",
      Instant::now(),
    );

    assert!(matches!(res.status, SurfaceStatus::Passed));
  }

  #[test]
  fn test_diff_check_via_tempcopy_default_formatter_error_is_violation() {
    // Non-opting callers keep today's behavior: a non-zero formatter exit
    // is `ViolationsFound`.
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("a.rs");
    std::fs::write(&file, "fn a() {}\n").unwrap();

    let res = diff_check_via_tempcopy(
      std::slice::from_ref(&file),
      |_scratch| Ok(scripted_output("", "boom", 2)),
      "rust",
      Instant::now(),
    );

    match res.status {
      SurfaceStatus::ViolationsFound { message, diff } => {
        assert!(diff.is_none());
        assert_eq!(message, "boom");
      }
      other => panic!("expected ViolationsFound, got {other:?}"),
    }
  }

  #[test]
  fn test_diff_check_via_tempcopy_classified_error_exit_and_both_streams() {
    // Opting in via `classify_all_nonzero_as_error`: the same non-zero exit
    // is now an `ExecutionError`, and both captured streams survive.
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("a.yaml");
    std::fs::write(&file, "a: 1\n").unwrap();

    let res = diff_check_via_tempcopy_classified(
      std::slice::from_ref(&file),
      |_scratch| Ok(scripted_output("BANNER", "PARSEFAIL", 2)),
      "yaml",
      Instant::now(),
      crate::surfaces::classify_all_nonzero_as_error,
    );

    match res.status {
      SurfaceStatus::ExecutionError { message } => {
        let out = message.find("BANNER").expect("stdout kept");
        let err = message.find("PARSEFAIL").expect("stderr kept");
        assert!(out < err, "stdout precedes stderr");
        assert!(message.contains("stderr:"), "stderr block labelled");
      }
      other => panic!("expected ExecutionError, got {other:?}"),
    }
  }

  #[test]
  fn test_diff_check_via_tempcopy_classified_violation_exit() {
    // A classifier can still route a specific code to `ViolationsFound`.
    let temp = TempDir::new().unwrap();
    let file = temp.path().join("a.rs");
    std::fs::write(&file, "fn a() {}\n").unwrap();

    let res = diff_check_via_tempcopy_classified(
      std::slice::from_ref(&file),
      |_scratch| Ok(scripted_output("drift", "", 1)),
      "rust",
      Instant::now(),
      crate::surfaces::classify_exit_one_as_violation,
    );

    match res.status {
      SurfaceStatus::ViolationsFound { message, .. } => {
        assert_eq!(message, "drift");
      }
      other => panic!("expected ViolationsFound, got {other:?}"),
    }
  }

  fn synced(name: &str, created: bool, ms: u64) -> SurfaceResult {
    SurfaceResult {
      surface_name: "test",
      status: SurfaceStatus::ConfigSynced {
        files: vec![SyncedConfigFile::new(name, created)],
      },
      duration: std::time::Duration::from_millis(ms),
    }
  }

  #[test]
  fn test_merge_sync_results_keeps_every_filename() {
    // Fixes #130: a surface that syncs two files used to return only the
    // second result, so the first file was created on disk and named
    // nowhere in the output.
    let merged = merge_sync_results(vec![
      synced(".markdownlint.json", true, 3),
      synced(".prettierrc.json", false, 4),
    ]);

    assert_eq!(
      merged.status.synced_file_names(),
      [".markdownlint.json", ".prettierrc.json"]
    );
    assert_eq!(merged.status.created_file_names(), [".markdownlint.json"]);
    assert_eq!(merged.surface_name, "test");
    // Durations sum: the row's time covers all the work the surface did.
    assert_eq!(merged.duration, std::time::Duration::from_millis(7));
  }

  #[test]
  fn test_merge_sync_results_all_already_in_sync_is_passed() {
    let already = |ms| SurfaceResult {
      surface_name: "test",
      status: SurfaceStatus::Passed,
      duration: std::time::Duration::from_millis(ms),
    };
    let merged = merge_sync_results(vec![already(1), already(2)]);
    assert!(matches!(merged.status, SurfaceStatus::Passed));
    assert!(merged.status.synced_file_names().is_empty());
    assert_eq!(merged.duration, std::time::Duration::from_millis(3));
  }

  #[test]
  fn test_merge_sync_results_reports_the_first_failure_verbatim() {
    // A failure already names its own file and the surface stops before
    // writing the rest, so it is surfaced as-is rather than merged.
    let drifted = SurfaceResult {
      surface_name: "test",
      status: SurfaceStatus::ConfigDrifted {
        file: ".clang-tidy".to_string(),
        diff: "--- a
+++ b
"
        .to_string(),
      },
      duration: std::time::Duration::from_millis(5),
    };
    let merged =
      merge_sync_results(vec![synced(".clang-format", true, 2), drifted]);
    assert!(matches!(
      merged.status,
      SurfaceStatus::ConfigDrifted { ref file, .. } if file == ".clang-tidy"
    ));
    assert_eq!(merged.duration, std::time::Duration::from_millis(7));
  }
}
