//! One representation of a tool's settings, rendered to a config file or to
//! command-line arguments.
//!
//! Each surface builds a [`ToolConfig`] from the resolved formality config
//! once. `fml sync` writes it as the tool's native file; `fml fmt`/`lint`/
//! `fix` pass the same settings inline, in whichever argument shape the tool
//! accepts, so the two paths cannot disagree. `.editorconfig` aggregation is
//! owned by `super::editorconfig`.

use std::ffi;
use std::path;
use std::time;

use serde_json;
use serde_yaml;
use toml;

use crate::surfaces;

/// Header notice inserted at the top of auto-generated configuration files.
pub const AUTO_GENERATED_HEADER: &str = "# Auto-generated by formality. DO NOT EDIT.\n# Changes to this file may be overwritten. Configure formality.toml instead.\n\n";
/// Warning string inserted in auto-generated JSON configuration files.
pub const AUTO_GENERATED_JSON_COMMENT: &str = "WARNING: DO NOT EDIT THIS FILE DIRECTLY! Automatically generated and managed by formality (fml). Canonical source of truth: formality.toml. Run 'fml sync' to update.";

/// How a string value is written inline.
#[derive(Debug, Clone, Copy)]
pub enum Quote {
  /// Bare: `newline_style=Unix`.
  None,
  /// TOML/YAML literal: `quote-style='double'`.
  Single,
}

/// A tool's settings in file order, and the file they live in.
#[derive(Debug, PartialEq)]
pub struct ToolConfig {
  /// The native config file name, relative to the workspace root.
  file: &'static str,
  /// Settings, nested by dotted key.
  settings: toml::Table,
}

impl ToolConfig {
  /// Starts an empty config for the native file `file`.
  #[must_use]
  pub fn new(file: &'static str) -> Self {
    Self {
      file,
      settings: toml::Table::new(),
    }
  }

  /// Sets the dotted `key` (e.g. `format.quote-style`) to `value`, creating
  /// intermediate tables.
  #[must_use]
  pub fn set(mut self, key: &str, value: impl Into<toml::Value>) -> Self {
    let mut table = &mut self.settings;
    let mut parts = key.split('.').peekable();
    while let Some(part) = parts.next() {
      if parts.peek().is_none() {
        table.insert(part.to_string(), value.into());
        break;
      }
      table = table
        .entry(part)
        .or_insert_with(|| toml::Value::Table(toml::Table::new()))
        .as_table_mut()
        .expect("a dotted key's prefix is a table");
    }
    self
  }

  /// Returns the value at the dotted `key`.
  ///
  /// # Panics
  ///
  /// Panics if `key` was never set: inline keys are fixed per surface, so a
  /// miss is a bug in that surface's key list.
  #[must_use]
  pub fn get(&self, key: &str) -> &toml::Value {
    let mut parts = key.split('.');
    let first = parts.next().unwrap_or_default();
    parts
      .try_fold(self.settings.get(first), |value, part| {
        Some(value?.as_table()?.get(part))
      })
      .flatten()
      .unwrap_or_else(|| panic!("{}: no setting `{key}`", self.file))
  }

  /// Returns the table at `key` as its own config, for tools whose inline
  /// flags name keys without their section prefix.
  #[must_use]
  pub fn section(&self, key: &str) -> Self {
    Self {
      file: self.file,
      settings: self.get(key).as_table().cloned().unwrap_or_default(),
    }
  }

  /// Renders `key`'s value inline, quoting strings per `quote`.
  #[must_use]
  pub fn inline(&self, key: &str, quote: Quote) -> String {
    inline_value(self.get(key), quote)
  }

  /// Renders the list at `key` as its items joined by `sep` (a scalar renders
  /// as itself).
  #[must_use]
  pub fn join(&self, key: &str, sep: &str) -> String {
    match self.get(key) {
      toml::Value::Array(items) => items
        .iter()
        .map(|v| inline_value(v, Quote::None))
        .collect::<Vec<_>>()
        .join(sep),
      value => inline_value(value, Quote::None),
    }
  }

  /// Renders `keys` as `key=value` pairs, dropping keys never set.
  #[must_use]
  pub fn pairs(&self, keys: &[&str], quote: Quote) -> Vec<String> {
    keys
      .iter()
      .filter(|key| self.contains(key))
      .map(|key| format!("{key}={}", self.inline(key, quote)))
      .collect()
  }

  /// Renders `keys` as `key=value` pairs, each preceded by `flag`
  /// (`--config a=1 --config b=2`).
  #[must_use]
  pub fn flagged(
    &self,
    flag: &str,
    keys: &[&str],
    quote: Quote,
  ) -> Vec<String> {
    self
      .pairs(keys, quote)
      .into_iter()
      .flat_map(|pair| [flag.to_string(), pair])
      .collect()
  }

  /// Renders `(flag, key)` pairs as long options: `--flag=value`, or a
  /// bare `--flag` for `true` and nothing for `false`.
  #[must_use]
  pub fn flags(&self, pairs: &[(&str, &str)]) -> Vec<String> {
    pairs
      .iter()
      .filter_map(|(flag, key)| match self.get(key) {
        toml::Value::Boolean(true) => Some(format!("--{flag}")),
        toml::Value::Boolean(false) => None,
        value => Some(format!("--{flag}={}", inline_value(value, Quote::None))),
      })
      .collect()
  }

  /// Returns the top-level settings as `(key, rendered value)` pairs.
  pub fn entries(&self) -> impl Iterator<Item = (&str, String)> {
    self
      .settings
      .iter()
      .map(|(k, v)| (k.as_str(), inline_value(v, Quote::None)))
  }

  /// Renders the top-level settings as one flow-style map, `{K: v, ...}`.
  #[must_use]
  pub fn flow(&self, quote: Quote) -> String {
    let entries: Vec<String> = self
      .settings
      .iter()
      .map(|(k, v)| format!("{k}: {}", inline_value(v, quote)))
      .collect();
    format!("{{{}}}", entries.join(", "))
  }

  /// Renders the settings as a YAML document without the generated-file
  /// header, for tools that take a whole config inline.
  #[must_use]
  pub fn yaml(&self) -> String {
    serde_yaml::to_string(&self.settings).unwrap_or_default()
  }

  /// Renders the native file's content, in the format its name implies,
  /// with the generated-file header (or `$comment` for JSON).
  #[must_use]
  pub fn render(&self) -> String {
    let ext = path::Path::new(self.file)
      .extension()
      .and_then(ffi::OsStr::to_str);
    if ext == Some("json") {
      let mut out =
        serde_json::to_string_pretty(&self.settings).unwrap_or_default();
      out.push('\n');
      out
    } else if matches!(ext, Some("yaml" | "yml"))
      || self.file.starts_with(".clang")
    {
      format!("{AUTO_GENERATED_HEADER}{}", self.yaml())
    } else {
      let body = toml::to_string_pretty(&self.settings).unwrap_or_default();
      format!("{AUTO_GENERATED_HEADER}{body}")
    }
  }

  /// Returns whether the dotted `key` was set.
  fn contains(&self, key: &str) -> bool {
    let mut parts = key.split('.');
    let first = parts.next().unwrap_or_default();
    parts
      .try_fold(self.settings.get(first), |value, part| {
        Some(value?.as_table()?.get(part))
      })
      .flatten()
      .is_some()
  }

  /// Writes (or with `check`, compares) the native file under the root.
  #[must_use]
  pub fn sync(
    &self,
    ctx: &surfaces::ExecutionContext,
    check: bool,
    start: time::Instant,
    surface_name: &'static str,
  ) -> surfaces::SurfaceResult {
    sync_file(ctx, self.file, &self.render(), check, start, surface_name)
  }
}

/// Converts a count to a TOML integer, saturating at `i64::MAX`.
#[must_use]
pub fn int(n: usize) -> toml::Value {
  toml::Value::Integer(i64::try_from(n).unwrap_or(i64::MAX))
}

/// Writes (or with `check`, compares) `content` as `file` under the root.
#[must_use]
pub fn sync_file(
  ctx: &surfaces::ExecutionContext,
  file: &'static str,
  content: &str,
  check: bool,
  start: time::Instant,
  surface_name: &'static str,
) -> surfaces::SurfaceResult {
  super::sync_file_helper(
    &ctx.root.join(file),
    file,
    content,
    check,
    start,
    surface_name,
  )
}

/// Writes `content` to a fresh temp file named `<prefix>…<suffix>`, for
/// tools that only take a config path; the file is deleted when the returned
/// guard drops.
///
/// # Errors
///
/// Returns the I/O error from creating or writing the file.
pub fn temp_file(
  prefix: &str,
  suffix: &str,
  content: &str,
) -> std::io::Result<tempfile::NamedTempFile> {
  let mut file = tempfile::Builder::new()
    .prefix(prefix)
    .suffix(suffix)
    .tempfile()?;
  std::io::Write::write_all(&mut file, content.as_bytes())?;
  std::io::Write::flush(&mut file)?;
  Ok(file)
}

/// Renders one value inline: scalars bare (strings per `quote`), arrays as
/// `[a,b]`.
fn inline_value(value: &toml::Value, quote: Quote) -> String {
  match value {
    toml::Value::String(s) => match quote {
      Quote::None => s.clone(),
      Quote::Single => format!("'{s}'"),
    },
    toml::Value::Array(items) => {
      let items: Vec<String> =
        items.iter().map(|v| inline_value(v, quote)).collect();
      format!("[{}]", items.join(","))
    }
    other => other.to_string(),
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  fn sample(file: &'static str) -> ToolConfig {
    ToolConfig::new(file)
      .set("width", 100)
      .set("style", "Unix")
      .set("format.quote-style", "double")
      .set("lint.select", vec!["E", "F"])
  }

  #[test]
  fn render_picks_the_format_from_the_file_name() {
    let cases = [
      ("a.toml", AUTO_GENERATED_HEADER, "width = 100"),
      ("a.yaml", AUTO_GENERATED_HEADER, "width: 100"),
      (".clang-format", AUTO_GENERATED_HEADER, "width: 100"),
      ("a.json", "{", "\"width\": 100"),
    ];
    for (file, prefix, line) in cases {
      let out = sample(file).render();
      assert!(out.starts_with(prefix), "{file}:\n{out}");
      assert!(out.contains(line), "{file}:\n{out}");
    }
  }

  #[test]
  fn render_keeps_insertion_order() {
    let out = sample("a.toml").render();
    let width = out.find("width").unwrap();
    let style = out.find("style").unwrap();
    assert!(width < style, "{out}");
  }

  #[test]
  fn yaml_has_no_document_marker() {
    let out = sample("a.yaml").render();
    assert!(!out.contains("---"), "{out}");
  }

  #[test]
  fn inline_renderings_table() {
    let cfg = sample("a.toml");
    let cases = [
      (cfg.inline("width", Quote::Single), "100"),
      (cfg.inline("style", Quote::None), "Unix"),
      (cfg.inline("style", Quote::Single), "'Unix'"),
      (cfg.inline("format.quote-style", Quote::Single), "'double'"),
      (cfg.inline("lint.select", Quote::Single), "['E','F']"),
      (
        cfg
          .pairs(&["width", "missing", "style"], Quote::None)
          .join(","),
        "width=100,style=Unix",
      ),
      (
        ToolConfig::new("x")
          .set("A", 1)
          .set("B", "b")
          .flow(Quote::None),
        "{A: 1, B: b}",
      ),
      (
        cfg.flagged("-o", &["width"], Quote::None).join(" "),
        "-o width=100",
      ),
      (cfg.join("lint.select", ","), "E,F"),
      (
        cfg
          .section("format")
          .pairs(&["quote-style"], Quote::None)
          .join(""),
        "quote-style=double",
      ),
      (
        ToolConfig::new("x")
          .set("on", true)
          .set("off", false)
          .set("n", 2)
          .flags(&[("on", "on"), ("off", "off"), ("n", "n")])
          .join(" "),
        "--on --n=2",
      ),
    ];
    for (actual, expected) in cases {
      assert_eq!(actual, expected);
    }
  }

  #[test]
  #[should_panic(expected = "no setting `absent`")]
  fn get_panics_on_an_unset_key() {
    let _ = sample("a.toml").get("absent");
  }
}
